Repository kitodo/kitodo-presentation, pull requests merged in 2018-05, with the labels that each got.

#274 Fix #273 multilanguage support of collection records
  Configuration/TCA/tx_dlf_collections.php
  common/class.tx_dlf_document.php
  modules/indexing/index.php
  plugins/collection/class.tx_dlf_collection.php
Labels: enhancement

#277 Fix #276 - TOC plugin flexform should not require a template
  plugins/toc/flexform.xml
Labels: bug

#281 Fix language overlay for collections
  plugins/collection/class.tx_dlf_collection.php
Labels: bug

#284 fix #283: compare value with simple array
  common/class.tx_dlf_list.php
Labels: bug

#278 Try to match documents by location
  common/class.tx_dlf_document.php
Labels: bug, enhancement

#285 Add possibility to use different fulltext formats
  common/class.tx_dlf_alto.php
  common/class.tx_dlf_document.php
  common/class.tx_dlf_fulltext.php
  common/class.tx_dlf_indexing.php
Labels: enhancement
