Repository kitodo/kitodo-presentation, pull requests merged in 2019-10, with the labels that each got.

#391 Use PageRenderer to add JavaScript and CSS file to page header/footer.
  Classes/Plugin/AudioPlayer.php
  Classes/Plugin/PageView.php
  Classes/Plugin/Search.php
  Configuration/TypoScript/setup.txt
  Resources/Private/Templates/AudioPlayer.tmpl
  Resources/Private/Templates/PageView.tmpl
Labels: maintenance

#393 Add a new tool "search in document".
  Classes/Common/Solr.php
  Classes/Plugin/Eid/SearchInDocument.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
  Configuration/Flexforms/Toolbox.xml
  Documentation/Plugins/Index.rst
  Resources/Private/Language/Labels.xml
  Resources/Private/Language/SearchInDocumentTool.xml
  Resources/Private/Templates/SearchInDocumentTool.tmpl
  Resources/Public/Javascript/Search/SearchInDocument.js
  ext_localconf.php
Labels: feature

#394 License and Rights Information
  Classes/Common/Document.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Plugin/OaiPmh.php
  Configuration/ApacheSolr/configsets/dlf/conf/schema.xml
  Configuration/TCA/tx_dlf_documents.php
  Configuration/TCA/tx_dlf_metadataformat.php
  Resources/Private/Data/MetadataDefaults.php
  Resources/Private/Language/Labels.xml
  ext_tables.sql
Labels: feature

#392 Workaround for toolbox plugin bug (if using custom template)
  Classes/Common/AbstractPlugin.php
  Classes/Plugin/Tools/AnnotationTool.php
  Classes/Plugin/Tools/FulltextTool.php
  Classes/Plugin/Tools/ImageDownloadTool.php
  Classes/Plugin/Tools/ImageManipulationTool.php
  Classes/Plugin/Tools/PdfDownloadTool.php
Labels: bug

#403 Fix loop on indexing documents
  hooks/class.tx_dlf_tcemain.php
Labels: bug

#405 Add ephemera as default structure element for new clients.
  Resources/Private/Data/StructureDefaults.php
  Resources/Private/Language/NewTenant.xml
Labels: feature

#401 Add support for linking URIs
  Classes/Common/Document.php
  Classes/Common/Indexer.php
  Classes/Format/Mods.php
  Classes/Plugin/Metadata.php
  Resources/Private/Data/MetadataDefaults.php
Labels: feature

#409 Backport GND support for 2.x
  common/class.tx_dlf_document.php
  common/class.tx_dlf_indexing.php
  common/class.tx_dlf_mods.php
  modules/newclient/metadata.inc.php
Labels: backport, feature

#408 Fix handling of tools' templates
  Classes/Common/AbstractPlugin.php
  Classes/Plugin/Tools/AnnotationTool.php
  Classes/Plugin/Tools/FulltextTool.php
  Classes/Plugin/Tools/ImageDownloadTool.php
  Classes/Plugin/Tools/ImageManipulationTool.php
  Classes/Plugin/Tools/PdfDownloadTool.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TypoScript/Toolbox/setup.txt
Labels: bug

#411 Check for type of instance to avoid loading unnecessary JavaScript.
  Classes/Plugin/PageView.php
Labels: bug

#412 Fixes #410 - replace ES6 style class and add Polyfills
  Resources/Public/Javascript/PageView/AnnotationControl.js
  Resources/Public/Javascript/PageView/OL3Sources.js
Labels: bug

#407 Fix calendar view of newspaper and ephemera
  Configuration/TCA/tx_dlf_documents.php
  common/class.tx_dlf_document.php
  ext_tables.sql
  locallang.xml
  plugins/newspaper/class.tx_dlf_newspaper.php
  plugins/newspaper/flexform.xml
  plugins/newspaper/locallang.xml
  plugins/newspaper/template.tmpl
Labels: maintenance

#413 Ensure unique element ids for IIIF annotation highlighting
  Resources/Public/Javascript/PageView/AnnotationParser.js
Labels: bug

#404 Handle HTML entities in fulltext properly
  Classes/Common/Indexer.php
  Configuration/ApacheSolr/configsets/dlf/conf/schema.xml
Labels: bug, security

#414 Extract @LABEL and @ORDERLABEL from METS
  Classes/Common/Document.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
  Configuration/TCA/tx_dlf_documents.php
  Resources/Private/Language/Labels.xml
  ext_tables.sql
Labels: feature
