Repository kitodo/kitodo-presentation, pull requests merged in 2019-09, with the labels that each got.

#375 Fix return type for array of old format classes
  class.ext_update.php
Labels: bug

#376 Replace deprecated calls to $GLOBALS['TYPO3'] select
  Classes/Common/AbstractPlugin.php
  Classes/Common/Document.php
  Classes/Common/DocumentList.php
  Classes/Common/DocumentTypeCheck.php
  Classes/Common/Helper.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Module/NewTenant.php
  Classes/Plugin/Basket.php
  Classes/Plugin/Calendar.php
  Classes/Plugin/Collection.php
  Classes/Plugin/Feeds.php
  Classes/Plugin/ListView.php
  Classes/Plugin/Metadata.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/Search.php
  Classes/Plugin/Statistics.php
Labels: maintenance

#366 Replace old CLI by Symfony Command Controller
  .gitignore
  Classes/Cli/CommandLineIndexer.php
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Hooks/ConfigurationForm.php
  Configuration/Commands.php
  Documentation/Developer/Index.rst
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
  Documentation/Plugins/Index.rst
  Documentation/Readme.rst
  Documentation/Settings.cfg
  Documentation/Settings.yml
  Documentation/Targets.rst
  Documentation/User/Index.rst
  Resources/Private/Language/FlashMessages.xml
  Resources/Private/Language/Labels.xml
  composer.json
  ext_conf_template.txt
  ext_localconf.php
Labels: maintenance

#377 Fix two SQL queries
  Classes/Common/Helper.php
  Classes/Plugin/Collection.php
Labels: bug

#380 Replase MySQL FIELD() by sorting the resulting array
  Classes/Plugin/Collection.php
Labels: bug

#382 Several fixes on using the queryBuilder
  Classes/Common/AbstractPlugin.php
  Classes/Common/Document.php
  Classes/Common/DocumentTypeCheck.php
  Classes/Hooks/DataHandler.php
  Classes/Plugin/Collection.php
  Classes/Plugin/OaiPmh.php
Labels: bug

#358 Backport database optimization from #354
  Configuration/TCA/tx_dlf_actionlog.php
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_documents.php
  Configuration/TCA/tx_dlf_formats.php
  Configuration/TCA/tx_dlf_metadata.php
  Configuration/TCA/tx_dlf_metadataformat.php
  ext_tables.sql
  plugins/newspaper/class.tx_dlf_newspaper.php
  plugins/oai/class.tx_dlf_oai.php
Labels: feature
