Repository kitodo/kitodo-presentation, pull requests merged in 2019-11, with the labels that each got.

#418 Support multiple DMDID
  Classes/Common/MetsDocument.php
  Classes/Hooks/KitodoProductionHacks.php
Labels: feature

#421 Fix index_search field length.
  Configuration/TCA/tx_dlf_collections.php
  ext_tables.sql
Labels: bug

#422 Add filter to make selection of collections easier.
  Configuration/Flexforms/Collection.xml
Labels: feature

#420 Fix scrutinizer issues
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Common/Document.php
  Classes/Common/DocumentList.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr.php
  Classes/Format/Mods.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/KitodoProductionHacks.php
  Classes/Plugin/ListView.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/Search.php
  Classes/Plugin/TableOfContents.php
  class.ext_update.php
  ext_localconf.php
  ext_tables.php
Labels: bug, maintenance

#423 Fix scrutinizer issues
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Common/AbstractModule.php
  Classes/Common/AbstractPlugin.php
  Classes/Common/Document.php
  Classes/Common/DocumentList.php
  Classes/Common/DocumentTypeCheck.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/IiifUrlReader.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Module/NewTenant.php
  Classes/Plugin/Basket.php
  Classes/Plugin/Calendar.php
  Classes/Plugin/Collection.php
  Classes/Plugin/Feeds.php
  Classes/Plugin/ListView.php
  Classes/Plugin/Metadata.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/Search.php
  Classes/Plugin/Statistics.php
Labels: maintenance

#426 Always check for valid xpath results
  Classes/Common/Document.php
  Classes/Common/MetsDocument.php
  Classes/Format/Alto.php
  Classes/Format/Mods.php
  Classes/Hooks/KitodoProductionHacks.php
  class.ext_update.php
Labels: bug

#429 Always show volumes of a collection.
  Classes/Plugin/Collection.php
Labels: bug

#430 Fix issues
  Classes/Common/Document.php
  Classes/Common/DocumentList.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr.php
  Classes/Module/NewTenant.php
  Resources/Private/Language/NewTenant.xml
Labels: bug

#432 2.x fix volume without parent
  common/class.tx_dlf_indexing.php
  plugins/collection/class.tx_dlf_collection.php
Labels: backport, bug

#433 PSR-12 code style
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Common/AbstractModule.php
  Classes/Common/AbstractPlugin.php
  Classes/Common/Document.php
  Classes/Common/DocumentList.php
  Classes/Common/DocumentTypeCheck.php
  Classes/Common/FulltextInterface.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/IiifUrlReader.php
  Classes/Common/Indexer.php
  Classes/Common/MetadataInterface.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr.php
  Classes/Format/Alto.php
  Classes/Format/Mods.php
  Classes/Format/TeiHeader.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ExtensionManagementUtility.php
  Classes/Hooks/FormEngine.php
  Classes/Hooks/KitodoProductionHacks.php
  Classes/Module/NewTenant.php
  Classes/Plugin/AudioPlayer.php
  Classes/Plugin/Basket.php
  Classes/Plugin/Calendar.php
  Classes/Plugin/Collection.php
  Classes/Plugin/Eid/PageViewProxy.php
  Classes/Plugin/Eid/SearchInDocument.php
  Classes/Plugin/Eid/SearchSuggest.php
  Classes/Plugin/Feeds.php
  Classes/Plugin/ListView.php
  Classes/Plugin/Metadata.php
  Classes/Plugin/Navigation.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/PageGrid.php
  Classes/Plugin/PageView.php
  Classes/Plugin/Search.php
  Classes/Plugin/Statistics.php
  Classes/Plugin/TableOfContents.php
  Classes/Plugin/Toolbox.php
  Classes/Plugin/Tools/AnnotationTool.php
  Classes/Plugin/Tools/FulltextTool.php
  Classes/Plugin/Tools/ImageDownloadTool.php
  Classes/Plugin/Tools/ImageManipulationTool.php
  Classes/Plugin/Tools/PdfDownloadTool.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
  Classes/Plugin/Validator.php
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_documents.php
  Configuration/TCA/tx_dlf_metadata.php
  class.ext_update.php
  ext_emconf.php
  ext_localconf.php
Labels: maintenance

#434 Turn empty search query into '*'
  Classes/Plugin/Search.php
Labels: bug

#435 Fix search truncation with '*' and '?'
  Classes/Common/Solr.php
Labels: bug

#436 Add support for seasonal newspapers and periodicals
  Classes/Plugin/Calendar.php
  Configuration/Flexforms/Calendar.xml
  Resources/Private/Language/Calendar.xml
  Resources/Private/Templates/Calendar.tmpl
Labels: feature

#437 Two backports to fix search issues in 2.x
  common/class.tx_dlf_solr.php
  plugins/search/class.tx_dlf_search.php
Labels: backport, bug

#438 Cleanup for release
  Classes/Common/AbstractPlugin.php
  Classes/Common/DocumentTypeCheck.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ItemsProcFunc.php
  Classes/Hooks/UserFunc.php
  Classes/Plugin/Eid/PageViewProxy.php
  Classes/Plugin/Eid/SearchInDocument.php
  Classes/Plugin/Eid/SearchSuggest.php
  Configuration/Commands.php
  Configuration/Flexforms/Collection.xml
  Configuration/Flexforms/Feeds.xml
  Configuration/Flexforms/OaiPmh.xml
  Configuration/Flexforms/Search.xml
  Configuration/Flexforms/Statistics.xml
  Configuration/Flexforms/Toolbox.xml
  Configuration/TCA/tx_dlf_documents.php
  Resources/Private/Data/StructureDefaults.php
  class.ext_update.php
  composer.json
  ext_localconf.php
Labels: bug, maintenance

#440 Scrutinizer Auto-Fixes
  Classes/Common/Document.php
  Classes/Common/DocumentList.php
  Classes/Common/Solr.php
  Configuration/Commands.php
Labels: maintenance

#439 Fix docTypeCheck for non-indexed documents
  Classes/Hooks/UserFunc.php
  Classes/Plugin/Calendar.php
  Classes/Plugin/PageView.php
  Resources/Private/Language/Labels.xml
  ext_localconf.php
Labels: bug

#441 add title with translation to 3 pageview interaction icons
  Classes/Plugin/PageView.php
Labels: feature

#443 Sort collection's entries by title initially
  Classes/Plugin/Collection.php
Labels: bug

#445 Backport: Sort collection's entries by title initially #443
  plugins/collection/class.tx_dlf_collection.php
Labels: backport, bug

#444 add title with translation to 8 navigation icons
  Classes/Plugin/Navigation.php
Labels: feature

#446 Add default extension icon and use for module
  Resources/Public/Icons/Extension.svg
  Resources/Public/Images/NewTenant.svg
  ext_tables.php
Labels: maintenance
