Repository kitodo/kitodo-presentation, pull requests merged in 2020-12, with the labels that each got.

#552 Fix condition check for adding full text control
  Resources/Public/Javascript/PageView/PageView.js
Labels: bug

#548 Fix scrolling to the highlighted full text element
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: bug

#556 Add FullTextUtility for methods common for full text plugins
  Classes/Plugin/PageView.php
  Resources/Public/Javascript/PageView/FullTextUtility.js
  Resources/Public/Javascript/PageView/FulltextControl.js
  Resources/Public/Javascript/PageView/PageView.js
Labels: maintenance

#557 Fix dlfUtils initialization to match Codacy standards
  Resources/Public/Javascript/PageView/Utility.js
Labels: maintenance

#558 Remove unused params in enableFulltextSelect method
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: maintenance

#560 Improve showFulltext method
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: maintenance

#561 Fix for SearchInDocument plugin if using routeEnhancers (Slug)
  Documentation/Configuration/Index.rst
  Resources/Public/Javascript/Search/SearchInDocument.js
Labels: maintenance

#550 Update Solarium to 5.1.6
  Classes/Common/Solr.php
  Resources/Private/Language/Labels.xml
  composer.json
  ext_conf_template.txt
Labels: maintenance

#562 Decrease complexity in FulltextControl
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: maintenance

#564 Disable coverage report in SonarCloud
  sonar-project.properties
Labels: maintenance

#555 Add Codacy Security Scan to Actions
  .github/workflows/code_analyzer.yml
Labels: maintenance

#572 Add the listview plugin to the new content element wizard.
  Configuration/TsConfig/ContentElements.tsconfig
  Resources/Private/Language/ListView.xml
  ext_localconf.php
Labels: bug

#569 Finish Solarium upgrade
  Classes/Common/DocumentList.php
  Classes/Common/Indexer.php
  Classes/Common/Solr.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Plugin/Collection.php
  Classes/Plugin/Eid/SearchInDocument.php
  Classes/Plugin/Eid/SearchSuggest.php
  Classes/Plugin/OaiPmh.php
  Resources/Private/Language/FlashMessages.xml
  Resources/Private/Language/Labels.xml
  Resources/Public/Javascript/Search/SearchInDocument.js
  Resources/Public/Javascript/Search/Suggester.js
  class.ext_update.php
  composer.json
  ext_conf_template.txt
Labels: bug, feature, maintenance

#573 Update README.md
  README.md
Labels: maintenance

#574 Add structure type "inventory" and "subinventory".
  Resources/Private/Data/StructureDefaults.php
  Resources/Private/Language/NewTenant.xml
Labels: feature

#571 Use numerical value for activation of the full text initially and add on/off behavior on link click
  Classes/Plugin/Tools/FulltextTool.php
  Configuration/TypoScript/Toolbox/setup.txt
  Documentation/Plugins/Index.rst
  Documentation/Settings.cfg
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: bug

#553 Make index_name editable
  Classes/Hooks/DataHandler.php
  Classes/Hooks/Form/FieldWizard/EditInProductionWarning.php
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_libraries.php
  Configuration/TCA/tx_dlf_metadata.php
  Configuration/TCA/tx_dlf_structures.php
  Resources/Private/Language/FlashMessages.xml
  Resources/Private/Language/Labels.xml
  ext_localconf.php
Labels: bug, feature
