Repository kitodo/kitodo-presentation, pull requests merged in 2020-03, with the labels that each got.

#485 Check for empty toolbox configuration.
  plugins/toolbox/tools/fulltext/class.tx_dlf_toolsFulltext.php
  plugins/toolbox/tools/imagedownload/class.tx_dlf_toolsImagedownload.php
  plugins/toolbox/tools/imagemanipulation/class.tx_dlf_toolsImagemanipulation.php
  plugins/toolbox/tools/pdf/class.tx_dlf_toolsPdf.php
Labels: maintenance

#486 Fix Image Manipuation Tool (again).
  Resources/Public/Javascript/PageView/ImageManipulationControl.js
Labels: bug

#487 Fix Codacy Issue
  Classes/Module/NewTenant.php
  Resources/Private/Data/MetadataDefaults.php
  Resources/Private/Data/StructureDefaults.php
Labels: maintenance

#490 Better markup for listview pagebrowser.
  Classes/Plugin/ListView.php
Labels: feature

#489 Fix codacy security issues
  Resources/Public/Javascript/AudioPlayer/AudioPlayer.js
  Resources/Public/Javascript/PageView/AltoParser.js
  Resources/Public/Javascript/PageView/AnnotationControl.js
  Resources/Public/Javascript/PageView/AnnotationParser.js
  Resources/Public/Javascript/PageView/FulltextControl.js
  Resources/Public/Javascript/PageView/ImageManipulationControl.js
  Resources/Public/Javascript/PageView/OL3.js
  Resources/Public/Javascript/PageView/OL3Sources.js
  Resources/Public/Javascript/PageView/PageView.js
  Resources/Public/Javascript/PageView/Utility.js
  Resources/Public/Javascript/Search/SearchInDocument.js
  Resources/Public/Javascript/Search/Suggester.js
Labels: maintenance

#491 Listview numeration
  Classes/Plugin/ListView.php
Labels: bug

#493 Fill orderlabel for sub-entries in TableOfContents plugin.
  Classes/Plugin/TableOfContents.php
Labels: bug

#494 Fix JavaScript error introduced with PR #487.
  Resources/Public/Javascript/PageView/OL3.js
Labels: bug

#495 Upgrade jQuery to 3.4.1
  Configuration/TypoScript/setup.txt
  Resources/Public/Javascript/PageView/PageView.js
  Resources/Public/Javascript/PageView/Utility.js
  Resources/Public/Javascript/jQuery/jquery-2.2.4.min.js
  Resources/Public/Javascript/jQuery/jquery-3.4.1.min.js
Labels: maintenance

#496 Fix the searchInDocument tool on initial page.
  Classes/Plugin/Tools/SearchInDocumentTool.php
Labels: bug

#497 Backport: Fix the searchInDocument tool on iniital page.
  plugins/toolbox/tools/searchindocument/class.tx_dlf_toolsSearchindocument.php
Labels: bug
