Repository kitodo/kitodo-presentation, pull requests merged in 2020-05, with the labels that each got.

#507 Add option to put JS in template
  Classes/Plugin/AudioPlayer.php
  Classes/Plugin/PageView.php
  Configuration/Flexforms/AudioPlayer.xml
  Configuration/Flexforms/PageView.xml
  Resources/Private/Language/AudioPlayer.xml
  Resources/Private/Language/PageView.xml
  Resources/Private/Templates/AudioPlayer.tmpl
  Resources/Private/Templates/PageView.tmpl
Labels: feature

#513 Show information if nothing was found in SearchInDocument tool.
  Classes/Plugin/Tools/SearchInDocumentTool.php
  Resources/Private/Language/SearchInDocumentTool.xml
  Resources/Private/Templates/SearchInDocumentTool.tmpl
  Resources/Public/Javascript/Search/SearchInDocument.js
Labels: feature

#503 $GLOBALS['TYPO3_DB'] in OaiPmh.php
  Classes/Plugin/OaiPmh.php
Labels: maintenance

#515 Feed plugin db fix
  Classes/Common/MetsDocument.php
  Classes/Plugin/Feeds.php
  ext_emconf.php
Labels: maintenance

#518 Update dependency versions
  composer.json
Labels: maintenance, security

#511 Use string value of header
  Classes/Plugin/Eid/PageViewProxy.php
Labels: bug

#514 Remove deprecated parameter
  Classes/Common/Helper.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Plugin/Basket.php
  Classes/Plugin/Calendar.php
  Classes/Plugin/Collection.php
  Classes/Plugin/ListView.php
  Classes/Plugin/Navigation.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/PageGrid.php
  Classes/Plugin/PageView.php
  Classes/Plugin/Search.php
  Classes/Plugin/Statistics.php
  Classes/Plugin/TableOfContents.php
  Classes/Plugin/Tools/AnnotationTool.php
  Classes/Plugin/Tools/FulltextTool.php
  Classes/Plugin/Tools/ImageManipulationTool.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
  class.ext_update.php
Labels: maintenance

#517 Make target container for image manipulation control configurable
  Classes/Plugin/Tools/AnnotationTool.php
  Classes/Plugin/Tools/ImageDownloadTool.php
  Classes/Plugin/Tools/ImageManipulationTool.php
  Resources/Public/Javascript/PageView/ImageManipulationControl.js
  Resources/Public/Javascript/PageView/Utility.js
Labels: feature

#516 Content Element Wizard support
  Configuration/TsConfig/ContentElements.tsconfig
  Resources/Private/Language/AudioPlayer.xml
  Resources/Private/Language/Basket.xml
  Resources/Private/Language/Calendar.xml
  Resources/Private/Language/Collection.xml
  Resources/Private/Language/Feeds.xml
  Resources/Private/Language/Metadata.xml
  Resources/Private/Language/Navigation.xml
  Resources/Private/Language/OaiPmh.xml
  Resources/Private/Language/PageGrid.xml
  Resources/Private/Language/PageView.xml
  Resources/Private/Language/Search.xml
  Resources/Private/Language/Statistics.xml
  Resources/Private/Language/TableOfContents.xml
  Resources/Private/Language/Toolbox.xml
  Resources/Private/Language/Validator.xml
  Resources/Public/Icons/tx-dlf-audioplayer.svg
  Resources/Public/Icons/tx-dlf-basket.svg
  Resources/Public/Icons/tx-dlf-calendar.svg
  Resources/Public/Icons/tx-dlf-collection.svg
  Resources/Public/Icons/tx-dlf-feeds.svg
  Resources/Public/Icons/tx-dlf-listview.svg
  Resources/Public/Icons/tx-dlf-metadata.svg
  Resources/Public/Icons/tx-dlf-navigation.svg
  Resources/Public/Icons/tx-dlf-oaipmh.svg
  Resources/Public/Icons/tx-dlf-pagegrid.svg
  Resources/Public/Icons/tx-dlf-pageview.svg
  Resources/Public/Icons/tx-dlf-search.svg
  Resources/Public/Icons/tx-dlf-statistics.svg
  Resources/Public/Icons/tx-dlf-tableofcontents.svg
  Resources/Public/Icons/tx-dlf-toolbox.svg
  Resources/Public/Icons/tx-dlf-validator.svg
  ext_localconf.php
Labels: feature, maintenance

#521 Always use the index_name of the default language in collection plugin
  Classes/Plugin/Collection.php
Labels: bug

#519 Fix DB queries for 9.x
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Plugin/Basket.php
  Classes/Plugin/Feeds.php
Labels: maintenance

#522 Prepare release of 3.1.0
  Documentation/Community/Index.rst
  Documentation/Configuration/Index.rst
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
  Documentation/Settings.cfg
  README.md
  composer.json
  ext_emconf.php
Labels: maintenance
