Repository kitodo/kitodo-presentation, pull requests merged in 2020-04, with the labels that each got.

#501 Fix syntax error breaking TYPO3 8.7
  Classes/Common/MetsDocument.php
Labels: bug

#499 refactores $GLOBALS['TYPO3_DB'] to QueryBuilder
  .gitignore
  class.ext_update.php
  composer.json
  ext_emconf.php
Labels: maintenance

#504 Fix OAI Plugin for TYPO3 8.7LTS
  Classes/Plugin/OaiPmh.php
Labels: bug

#505 Add CORS header to file proxy
  Classes/Plugin/Eid/PageViewProxy.php
Labels: feature

#508 Fix value attribute of search input field
  Classes/Plugin/Search.php
Labels: bug

#506 Make usage of absolute links configurable
  Classes/Common/AbstractPlugin.php
  Classes/Plugin/Basket.php
  Classes/Plugin/Calendar.php
  Classes/Plugin/Collection.php
  Classes/Plugin/Feeds.php
  Classes/Plugin/ListView.php
  Classes/Plugin/Metadata.php
  Classes/Plugin/Navigation.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/PageGrid.php
  Classes/Plugin/PageView.php
  Classes/Plugin/Search.php
  Classes/Plugin/Tools/ImageDownloadTool.php
  Classes/Plugin/Tools/PdfDownloadTool.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
  Resources/Private/Language/Labels.xml
  ext_conf_template.txt
Labels: feature

#509 Replace deprecated ExtensionManagementUtility::siteRelPath()
  Classes/Plugin/AudioPlayer.php
  Classes/Plugin/Collection.php
  Classes/Plugin/OaiPmh.php
  Classes/Plugin/PageGrid.php
  Classes/Plugin/PageView.php
  Classes/Plugin/Search.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
Labels: maintenance

#510 Include fallback for TYPO3 8.7
  Classes/Common/AbstractPlugin.php
Labels: bug
