Repository kitodo/kitodo-presentation, pull requests merged in 2020-02, with the labels that each got.

#462 Register Plugins without addPItoST43().
  Classes/Hooks/ExtensionManagementUtility.php
  ext_localconf.php
  ext_tables.php
Labels: maintenance

#463 Small config changes for TYPO3 9.5 and 8.7.
  .gitignore
  Classes/Common/Helper.php
  composer.json
Labels: maintenance

#464 Convert eID-scripts to support PSR-7.
  Classes/Plugin/Eid/PageViewProxy.php
  Classes/Plugin/Eid/SearchInDocument.php
  Classes/Plugin/Eid/SearchSuggest.php
  Resources/Private/Templates/SearchInDocumentTool.tmpl
  Resources/Public/Javascript/Search/SearchInDocument.js
Labels: maintenance

#465 Three SQL-queries migrated to QueryBuilder.
  Classes/Common/Document.php
  Classes/Common/Helper.php
  Classes/Common/MetsDocument.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ItemsProcFunc.php
  ext_conf_template.txt
Labels: maintenance

#466 Show flashmessages on updating kitodo records in the backend.
  Classes/Common/Helper.php
  Classes/Common/Indexer.php
  Classes/Common/KitodoFlashMessageRenderer.php
Labels: bug, maintenance

#467 Make the newTenant module work with TYPO3 8.7 + 9.5.
  Classes/Common/AbstractModule.php
  Classes/Module/NewTenant.php
  ext_tables.php
Labels: maintenance

#468 Bootstrap on accessing the extension configuration in TYPO3 9.
  Classes/Common/Helper.php
  Classes/Hooks/ConfigurationForm.php
Labels: maintenance

#473 Fix SQL query in search plugin for facetCollections.
  Classes/Plugin/Search.php
Labels: bug

#475 Fix language overlay for list and single collection view.
  Classes/Plugin/Collection.php
Labels: bug

#470 Some more SQL queries converted to doctrine QueryBuilder.
  Classes/Hooks/DataHandler.php
  Classes/Plugin/Statistics.php
  Classes/Plugin/TableOfContents.php
Labels: maintenance

#476 Enhance the calendar plugin.
  Classes/Plugin/Calendar.php
  Configuration/Flexforms/Calendar.xml
  Resources/Private/Language/Calendar.xml
Labels: feature

#477 The year files are not sorted as volume_sorting is empty.
  Classes/Plugin/Calendar.php
Labels: bug

#479 Change target navigation of calendar plugin.
  Classes/Plugin/Calendar.php
  Resources/Private/Language/Calendar.xml
Labels: feature

#480 Remove not used method indexer::delete().
  Classes/Common/Indexer.php
Labels: maintenance

#481 Check for non-existing and empty "document_format"
  class.ext_update.php
Labels: bug

#482 Update Codacy badge
  README.md
Labels: maintenance

#484 Update Codacy badge (2.x)
  README.md
Labels: maintenance
