Repository kitodo/kitodo-presentation, pull requests merged in 2021-02, with the labels that each got.

#585 Add empty space after last span of the text line
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: bug

#586 Pass scroll id as param to method to avoid undefined value
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: bug

#576 Add core status widget
  Classes/Hooks/Form/FieldInformation/EditInProductionWarning.php
  Classes/Hooks/Form/FieldInformation/SolrCoreStatus.php
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_libraries.php
  Configuration/TCA/tx_dlf_metadata.php
  Configuration/TCA/tx_dlf_solrcores.php
  Configuration/TCA/tx_dlf_structures.php
  Resources/Private/Language/FlashMessages.xml
  Resources/Private/Language/Labels.xml
  ext_localconf.php
Labels: feature

#580 Use AES-256-CTR and SHA256
  Classes/Common/Document.php
  Classes/Common/Helper.php
  Classes/Common/Solr.php
  Classes/Plugin/Eid/SearchInDocument.php
  Classes/Plugin/Eid/SearchSuggest.php
  Classes/Plugin/Search.php
  Classes/Plugin/Tools/SearchInDocumentTool.php
  Resources/Private/Templates/SearchInDocumentTool.tmpl
Labels: maintenance, security

#591 Update issue templates
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/task-for-the-development-fund.md
Labels: development fund, maintenance

#593 Update .gitignore
  .gitignore
Labels: maintenance

#598 Remove solr.StandardFilterFactory as it is unused and breaks Solr 8.
  Configuration/ApacheSolr/configsets/dlf/conf/schema.xml
Labels: maintenance

#600 Update issue templates
  .github/ISSUE_TEMPLATE/task-for-the-development-fund.md
Labels: maintenance
