Repository kitodo/kitodo-presentation, pull requests merged in 2021-01, with the labels that each got.

#577 Remove double submit of the search form
  Resources/Public/Javascript/Search/SearchInDocument.js
Labels: bug

#581 Make scroll element for full text scrolling configurable
  Classes/Plugin/Tools/FulltextTool.php
  Configuration/TypoScript/Toolbox/setup.txt
  Documentation/Plugins/Index.rst
  Resources/Public/Javascript/PageView/FulltextControl.js
Labels: feature

#579 Add support for Solarium 4.2
  Classes/Common/Solr.php
  composer.json
Labels: backport

#583 Add Solr core name on calculation the cache identifier.
  Classes/Common/Solr.php
Labels: bug
