Repository kitodo/kitodo-presentation, pull requests merged in 2022-08, with the labels that each got.

#686 Create View3D plugin
  Classes/Controller/View3DController.php
  Resources/Private/Templates/View3D/Main.html
  Resources/Public/Icons/tx-dlf-view3d.svg
  ext_localconf.php
Labels: feature

#796 [FEATURE] Also process amdSec (not only dmdSec)
  Build/Documentation/dbdocs/Generator.php
  Classes/Common/MetsDocument.php
  Classes/Domain/Model/Metadata.php
  Classes/Format/AudioVideoMD.php
  DEVELOPMENT.md
  Documentation/Developers/Database.rst
  Tests/Fixtures/MetsDocument/av_beispiel.xml
  Tests/Fixtures/MetsDocument/metadata_mets.xml
  Tests/Fixtures/MetsDocument/two_dmdsec.xml
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/FunctionalTestCase.php
Labels: feature

#821 [BUGFIX] Fix various issues in page view and search
  Classes/Command/BaseCommand.php
  Classes/Common/Doc.php
  Classes/Common/Helper.php
  Classes/Common/MetsDocument.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/SearchController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Classes/Domain/Repository/DocumentRepository.php
  Resources/Private/Partials/TableOfContents/Children.html
  Resources/Private/Partials/TableOfContents/Title.html
  Resources/Private/Templates/Navigation/Main.html
  Tests/Functional/Common/HelperTest.php
Labels: bug

#831 [FEATURE] Allow to override OL controls, pass translations to PageView
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/PageView/Main.html
  Resources/Public/Javascript/PageView/PageView.js
  Resources/Public/Javascript/PageView/Utility.js
Labels: feature

#832 [FEATURE] Implement loading indicator for page view
  Classes/Controller/PageViewController.php
  Configuration/Flexforms/PageView.xml
  Documentation/Features/PageView.rst
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Public/Javascript/PageView/PageView.js
  Resources/Public/Javascript/PageView/Utility.js
Labels: feature

#843 [BUGFIX] Show metadata entry only if values are not empty
  Documentation/Developers/Metadata.rst
  Resources/Private/Partials/Metadata/Entries.html
Labels: bug

#840 [PERFORMANCE] Use Solr grouping to improve/fix search performance
  Classes/Common/SolrSearch.php
  Classes/Common/SolrSearchQuery.php
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
  Classes/Domain/Repository/DocumentRepository.php
  Resources/Private/Partials/ListView/Results.html
  Tests/Functional/Common/SolrIndexingTest.php
Labels: bug, maintenance

#846 [BUGFIX] Don't rely on `LanguageService::create` in test
  .github/workflows/tests.yml
  Tests/Functional/Common/HelperTest.php
  Tests/Functional/FunctionalTestCase.php
Labels: bug

#847 [BUGFIX] Fix test case after renaming `SolrSearch::getNumHits()`
  Tests/Functional/Common/SolrIndexingTest.php
Labels: bug

#848 [BUGFIX] Missing labels in toolbox plugin
  Classes/Hooks/ItemsProcFunc.php
Labels: bug

#827 [BUGFIX] Clear document registry to prevent memory exhaustion
  Classes/Command/ReindexCommand.php
Labels: bug

#845 [BUGFIX] Multidomain typoscript configuration
  Classes/Hooks/ItemsProcFunc.php
Labels: bug

#844 [FEATURE] In calendar, fall back to METS if DB is empty
  Classes/Controller/CalendarController.php
Labels: feature, maintenance
