Repository kitodo/kitodo-presentation, pull requests merged in 2023-01, with the labels that each got.

#877 [MAINTENANCE] Fix directory naming for FlexForms and JavaScript
  .lgtm.yml
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/BasketController.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TypoScript/setup.typoscript
  Resources/Private/Templates/View3D/Main.html
  Resources/Public/Javascript/3DViewer/main.js
Labels: maintenance

#828 [FEATURE] Add reading of metadata from MODS for 3D objects
  Classes/Common/MetsDocument.php
  Classes/Format/Mods.php
  Resources/Private/Data/MetadataDefaults.php
Labels: feature

#829 [FEATURE] Integrate ORCID API
  Classes/Api/Orcid/Client.php
  Classes/Api/Orcid/Profile.php
  Classes/Format/Mods.php
  Resources/Private/Data/MetadataDefaults.php
Labels: feature

#869 [FEATURE] Integrate datesearch
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr.php
  Classes/Common/SolrSearch.php
  Classes/Controller/SearchController.php
  Configuration/ApacheSolr/configsets/dlf/conf/schema.xml
  Configuration/Flexforms/Search.xml
  Resources/Private/Data/MetadataDefaults.php
  Resources/Private/Language/Labels.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/de.locallang_metadata.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Language/locallang_metadata.xlf
  Resources/Private/Partials/ListView/SortingForm.html
  Resources/Private/Templates/Search/Main.html
  ext_conf_template.txt
Labels: feature

#870 [BUGFIX] Adaptation of the page navigation form
  Classes/Controller/NavigationController.php
  Classes/Domain/Model/PageSelectForm.php
  Resources/Private/Templates/Navigation/Main.html
  ext_localconf.php
Labels: bug

#871 [BUGFIX] Reactivate the "back to listview" link.
  Classes/Controller/ListViewController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/SearchController.php
  Resources/Private/Templates/Navigation/Main.html
Labels: bug

#888 [MAINTENANCE] Use \d instead 0-9 in regex
  Classes/Command/HarvestCommand.php
  Classes/Common/Helper.php
Labels: maintenance

#892 [MAINTENANCE] Change class attributes to match new package namespaces since solr-ocrhighlighting v0.8.0
  Build/Test/solr/contrib/ocrsearch/lib/solr-ocrhighlighting-0.7.1.jar
  Build/Test/solr/contrib/ocrsearch/lib/solr-ocrhighlighting-0.8.3-solr78.jar
  Configuration/ApacheSolr/configsets/dlf/conf/schema.xml
  Configuration/ApacheSolr/configsets/dlf/conf/solrconfig.xml
Labels: maintenance

#880 [BUGFIX] Fix missing translation of language code in resultset (ListView)
  Classes/Common/SolrSearch.php
Labels: bug

#838 [FEATURE] Improve API reading
  Classes/Api/Viaf/Profile.php
  Classes/Format/Mods.php
Labels: feature

#839 [FEATURE] Display links in metadata
  Classes/Controller/MetadataController.php
  Resources/Private/Partials/Metadata/Entries.html
  Resources/Private/Partials/Metadata/ExternalLinkEntry.html
Labels: feature

#861 [BUGFIX] Use title as title_sorting as default
  Classes/Common/MetsDocument.php
Labels: bug

#862 [MAINTENANCE] Don't use Image-Proxy for IIIF links
  Classes/Controller/PageViewController.php
Labels: maintenance

#876 [MAINTENANCE] Remove overview page for 3D models
  Classes/Controller/TableOfContentsController.php
  Resources/Private/Partials/TableOfContents/Filter.html
  Resources/Private/Partials/TableOfContents/Model.html
  Resources/Private/Partials/TableOfContents/Models.html
  Resources/Private/Templates/TableOfContents/Main.html
Labels: maintenance

#867 [MAINTENANCE] Update main.js with comments
  Resources/Public/Javascript/3DViewer/main.js
Labels: maintenance

#872 [BUGFIX] Fix reading of metadata files which has more than one child node
  Resources/Public/Javascript/3DViewer/main.js
Labels: bug

#889 [FEATURE] Update main.js
  Resources/Public/Javascript/3DViewer/main.js
Labels: feature
