Repository kitodo/kitodo-presentation, pull requests merged in 2023-09, with the labels that each got.

#964 [BUGFIX] Display issues correctly in ToC plugin
  Classes/Common/MetsDocument.php
  Classes/Controller/TableOfContentsController.php
  Classes/Domain/Repository/DocumentRepository.php
  Configuration/TypoScript/setup.typoscript
  Documentation/Plugins/Index.rst
Labels: 🐛 bug

#1020 [BUGFIX] PageRepository class moved to Core
  Classes/Common/Helper.php
Labels: 🐛 bug

#960 [MAINTENANCE] Change initialization of DocumentRepository in DocumentTypeFunctionProvider
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🛠 maintenance

#990 [MAINTENANCE] Rename Doc class to AbstractDocument
  Classes/Command/BaseCommand.php
  Classes/Command/HarvestCommand.php
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr/SolrSearch.php
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/BasketController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/FeedsController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Classes/Controller/View3DController.php
  Classes/Domain/Model/Document.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Classes/Hooks/DataHandler.php
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/Repository/DocumentRepositoryTest.php
Labels: 🛠 maintenance

#999 [DOCUMENTATION] Fix documentation for toolbox
  Documentation/Administrator/Index.rst
Labels: 📖 documentation

#1000 [BUGFIX] Reassign viewData['requestData'] after page is validated
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1001 [BUGFIX] Fix returns in controllers' main functions
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/SearchController.php
  Classes/Controller/ToolboxController.php
  Classes/Controller/View3DController.php
Labels: 🐛 bug

#1002 [FEATURE] Reimplement SearchInDocument tool to create results' links in backend
  Classes/Controller/ToolboxController.php
  Classes/Eid/SearchInDocument.php
  Configuration/TypoScript/Toolbox/setup.typoscript
  Resources/Private/Templates/Toolbox/Main.html
  Resources/Public/JavaScript/PageView/SearchInDocument.js
Labels: ⚙ feature

#1006 [MAINTENANCE] Remove not needed sanitize for double parameter
  Classes/Controller/NavigationController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/TableOfContentsController.php
Labels: 🛠 maintenance

#1008 [FEATURE] Use getFileInfo function for getting file url and mime type
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/ToolboxController.php
Labels: ⚙ feature

#1009 Display and index hyphenated words as normal words
  Classes/Format/Alto.php
  Resources/Public/JavaScript/PageView/AltoParser.js
  Resources/Public/JavaScript/PageView/FulltextControl.js
Labels: 🐛 bug

#1010 [MAINTENANCE] Consistently use namespace declaration and avoid namespaces in code
  Classes/Command/BaseCommand.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/IiifUrlReader.php
  Classes/Common/Indexer.php
  Classes/Common/KitodoFlashMessageRenderer.php
  Classes/Common/Solr/Solr.php
  Classes/Controller/AbstractController.php
  Classes/Controller/BasketController.php
  Classes/Controller/CollectionController.php
  Classes/Controller/FeedsController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/OaiPmhController.php
  Classes/Controller/ToolboxController.php
  Classes/Domain/Model/ActionLog.php
  Classes/Domain/Model/Basket.php
  Classes/Domain/Model/Collection.php
  Classes/Domain/Model/Document.php
  Classes/Domain/Model/Format.php
  Classes/Domain/Model/Library.php
  Classes/Domain/Model/Mail.php
  Classes/Domain/Model/Metadata.php
  Classes/Domain/Model/MetadataFormat.php
  Classes/Domain/Model/PageSelectForm.php
  Classes/Domain/Model/Printer.php
  Classes/Domain/Model/SolrCore.php
  Classes/Domain/Model/Structure.php
  Classes/Domain/Model/Token.php
  Classes/Domain/Repository/ActionLogRepository.php
  Classes/Domain/Repository/BasketRepository.php
  Classes/Domain/Repository/CollectionRepository.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Domain/Repository/FormatRepository.php
  Classes/Domain/Repository/LibraryRepository.php
  Classes/Domain/Repository/MailRepository.php
  Classes/Domain/Repository/MetadataFormatRepository.php
  Classes/Domain/Repository/MetadataRepository.php
  Classes/Domain/Repository/PrinterRepository.php
  Classes/Domain/Repository/SolrCoreRepository.php
  Classes/Domain/Repository/StructureRepository.php
  Classes/Domain/Repository/TokenRepository.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Classes/ExpressionLanguage/DocumentTypeProvider.php
  Classes/Format/AudioVideoMD.php
  Classes/Format/Mods.php
  Classes/Format/TeiHeader.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/Form/FieldInformation/EditInProductionWarning.php
  Classes/Hooks/Form/FieldInformation/SolrCoreStatus.php
  Classes/Hooks/ItemsProcFunc.php
  Classes/Updates/MigrateSettings.php
Labels: 🛠 maintenance

#1011 [MAINTENANCE] Remove {@inheritdoc} from functions
  Classes/Common/IiifManifest.php
  Classes/Common/IiifUrlReader.php
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1013 [MAINTENANCE] Unify and improve PHPDocs for class properties
  Classes/Api/Orcid/Client.php
  Classes/Api/Orcid/Profile.php
  Classes/Api/Viaf/Client.php
  Classes/Api/Viaf/Profile.php
  Classes/Command/BaseCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/IiifUrlReader.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr/SearchResult/Highlight.php
  Classes/Common/Solr/SearchResult/Page.php
  Classes/Common/Solr/SearchResult/Region.php
  Classes/Common/Solr/SearchResult/ResultDocument.php
  Classes/Common/Solr/Solr.php
  Classes/Common/Solr/SolrSearch.php
  Classes/Common/Solr/SolrSearchQuery.php
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/Backend/NewTenantController.php
  Classes/Controller/BasketController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/CollectionController.php
  Classes/Controller/FeedsController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/OaiPmhController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/SearchController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Classes/Domain/Model/ActionLog.php
  Classes/Domain/Model/Basket.php
  Classes/Domain/Model/Collection.php
  Classes/Domain/Model/Document.php
  Classes/Domain/Model/Format.php
  Classes/Domain/Model/Library.php
  Classes/Domain/Model/Mail.php
  Classes/Domain/Model/Metadata.php
  Classes/Domain/Model/MetadataFormat.php
  Classes/Domain/Model/PageSelectForm.php
  Classes/Domain/Model/Printer.php
  Classes/Domain/Model/SolrCore.php
  Classes/Domain/Model/Structure.php
  Classes/Domain/Model/Token.php
  Classes/Domain/Repository/CollectionRepository.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Eid/PageViewProxy.php
  Classes/Format/Mods.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ItemsProcFunc.php
  Classes/Updates/FileLocationUpdater.php
  Classes/ViewHelpers/StdWrapViewHelper.php
Labels: 🛠 maintenance

#1018 [MAINTENANCE] Consistently use type declaration for parameters and return values - part 1
  Classes/Api/Orcid/Client.php
  Classes/Api/Orcid/Profile.php
  Classes/Api/Viaf/Client.php
  Classes/Api/Viaf/Profile.php
  Classes/Command/BaseCommand.php
  Classes/Command/HarvestCommand.php
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/FulltextInterface.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/IiifUrlReader.php
  Classes/Common/Indexer.php
  Classes/Common/KitodoFlashMessageRenderer.php
  Classes/Common/MetadataInterface.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr/SearchResult/Highlight.php
  Classes/Common/Solr/SearchResult/Page.php
  Classes/Common/Solr/SearchResult/Region.php
  Classes/Common/Solr/SearchResult/ResultDocument.php
  Classes/Common/Solr/Solr.php
  Classes/Common/Solr/SolrSearch.php
  Classes/Common/Solr/SolrSearchQuery.php
  Classes/Common/SolrPaginator.php
  Classes/Eid/PageViewProxy.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Classes/Format/Alto.php
  Classes/Format/AudioVideoMD.php
  Classes/Format/Mods.php
  Classes/Format/TeiHeader.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ItemsProcFunc.php
  Classes/Hooks/KitodoProductionHacks.php
  Classes/Hooks/ThumbnailCustomElement.php
  Classes/Middleware/SearchInDocument.php
  Classes/Pagination/PageGridPaginator.php
  Classes/Updates/FileLocationUpdater.php
  Classes/ViewHelpers/JsFooterViewHelper.php
  Classes/ViewHelpers/MetadataWrapVariableViewHelper.php
  Classes/ViewHelpers/StdWrapViewHelper.php
  Tests/Functional/Common/SolrIndexingTest.php
Labels: 🛠 maintenance

#1019 [BUGFIX] Fix calls for Indexer::add function
  Classes/Command/BaseCommand.php
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1027 [BUGFIX] Fix returns in functions of IiifManifest class
  Classes/Common/IiifManifest.php
Labels: 🐛 bug
