Repository kitodo/kitodo-presentation, pull requests merged in 2023-12, with the labels that each got.

#1069 [BUGFIX] Change way of key generation for collection
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1098 [BUGFIX] Fix call to `ExtensionUtility::registerModule`
  ext_tables.php
Labels: 🐛 bug

#1099 [MAINTENANCE] Remove usage of deprecated `addQueryStringMethod`
  Resources/Private/Partials/TableOfContents/Children.html
  Resources/Private/Templates/Navigation/Main.html
Labels: 🛠 maintenance

#1100 [BUGFIX] Fix wrong caching backend and default lifetime
  ext_localconf.php
Labels: 🐛 bug

#953 [MAINTENANCE] Add tests for Common package
  Tests/Fixtures/Common/pages.csv
  Tests/Fixtures/Common/solrcores.csv
  Tests/Functional/Api/OaiPmhTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/Common/SolrSearchQueryTest.php
  Tests/Functional/Common/SolrSearchTest.php
  Tests/Functional/Common/SolrTest.php
Labels: 🛠 maintenance, ⭐ development fund 2022

#1109 [BUGFIX] Fix calendar view
  Classes/Controller/CalendarController.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#1110 [BUGFIX] Cast `uid` to int for searching title data and provide alternative source for title
  Classes/Controller/CalendarController.php
Labels: 🐛 bug

#1111 [BUGFIX] Revert changes on `errorAction` to fix #1082
  Classes/Controller/Backend/NewTenantController.php
Labels: 🐛 bug

#1112 [MAINTENANCE] Use generators for reading calendar issues
  Classes/Controller/CalendarController.php
Labels: 🛠 maintenance

#1113 [BUGFIX] Query children metadata in batches to avoid OutOfMemoryException
  Classes/Common/Solr/SolrSearch.php
  Documentation/Plugins/Index.rst
Labels: 🐛 bug

#1114 [MAINTENANCE] Replace `fetchAll()` with `fetchAllAssociative()`
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1102 [BUGFIX] Fix pagination in DFG-Viewer GridView
  Classes/Controller/AbstractController.php
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug
