Repository kitodo/kitodo-presentation, pull requests merged in 2023-10, with the labels that each got.

#1025 [BUGFIX] Fix initialization and checks for rawData in API profiles
  Classes/Api/Orcid/Profile.php
  Classes/Api/Viaf/Profile.php
Labels: 🐛 bug

#1026 [BUGFIX] Fix getting AbstractDocument instance from cache
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1028 [BUGFIX] Remove documentRepository from Indexer constructor
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1030 [MAINTENANCE] Update MetadataController with AbstractDocument usage
  Classes/Controller/MetadataController.php
Labels: 🛠 maintenance

#1031 [BUGFIX] Fix call findOneByIndexName
  Classes/Command/BaseCommand.php
Labels: 🐛 bug

#1032 [MAINTENANCE] Adds curly braces around blocks in loops and conditionals
  Resources/Public/JavaScript/PageView/AltoParser.js
  Resources/Public/JavaScript/PageView/AnnotationParser.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🛠 maintenance, ⭐ development fund 2023

#1033 [BUGFIX] Fix property type for feCruserId in Collection model
  Classes/Domain/Model/Collection.php
Labels: 🐛 bug

#1034 [BUGFIX] Fix namespaces in DocumentTypeFunctionProvider class
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#1035 [BUGFIX] Remove check for $this->document not null
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#1036 [BUGFIX] Fix var declaration for PageRender
  Classes/ViewHelpers/JsFooterViewHelper.php
Labels: 🐛 bug

#1037 [BUGFIX] Adds missing semicolons
  Resources/Public/JavaScript/PageView/AnnotationControl.js
  Resources/Public/JavaScript/PageView/AnnotationParser.js
  Resources/Public/JavaScript/PageView/FulltextControl.js
Labels: 🐛 bug, ⭐ development fund 2023

#1038 [BUGFIX] Removes unnecessary semicolons
  Resources/Public/JavaScript/PageView/AltoParser.js
  Resources/Public/JavaScript/PageView/AnnotationControl.js
Labels: 🐛 bug, ⭐ development fund 2023

#1039 [BUGFIX] Change check for empty result set
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1041 [SECURITY] Fixes security issues #4526, #4523 und #4522 reported by CodeQL
  Resources/Public/JavaScript/PageView/ImageManipulationControl.js
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/SearchInDocument.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: ⚡ security, ⭐ development fund 2023

#1051 [BUGFIX] Fixes incorrect usage of getFileLocation() instead of getFileInfo()
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1043 [MAINTENANCE] Check object properties before using them
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🛠 maintenance, ⭐ development fund 2023

#1044 [MAINTENANCE] Fixes ESLint_camelcase warnings
  Resources/Public/JavaScript/PageView/AltoParser.js
  Resources/Public/JavaScript/PageView/AnnotationParser.js
  Resources/Public/JavaScript/PageView/ImageManipulationControl.js
  Resources/Public/JavaScript/PageView/OL.js
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🛠 maintenance, ⭐ development fund 2023

#1047 [MAINTENANCE] Fix docs and types in AbstractDocument and its child classes
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance, 📖 documentation

#1048 [MAINTENANCE] Fixes Phpmd CamelCaseParameterName Warnings
  Classes/Common/Helper.php
  Classes/Common/Indexer.php
  Classes/Controller/BasketController.php
  Classes/Hooks/KitodoProductionHacks.php
Labels: 🛠 maintenance, ⭐ development fund 2023

#1049 [MAINTENANCE] Fixes Phpmd CamelCaseMethodName warnings
  Classes/Common/MetsDocument.php
  Classes/Common/Solr/Solr.php
  Classes/Controller/CollectionController.php
  Classes/Controller/OaiPmhController.php
  Classes/Hooks/KitodoProductionHacks.php
Labels: 🛠 maintenance, ⭐ development fund 2023

#1050 [BUGFIX] Fixes wrong type and missing initialization of $recordId
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1045 [MAINTENANCE] Consistently use type declaration for parameters and return values - part 2
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/Backend/NewTenantController.php
  Classes/Controller/BasketController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/CollectionController.php
  Classes/Controller/FeedsController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/SearchController.php
  Classes/Controller/StatisticsController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Classes/Controller/View3DController.php
  Classes/Domain/Model/Document.php
  Classes/Domain/Model/Metadata.php
  Classes/Domain/Repository/CollectionRepository.php
  Classes/Domain/Repository/MailRepository.php
  Classes/Domain/Repository/MetadataRepository.php
  Classes/Domain/Repository/TokenRepository.php
Labels: 🛠 maintenance

#1058 [BUGFIX] Fixes incomplete renaming $index_name to $indexName of #1048
  Classes/Common/Helper.php
Labels: 🐛 bug, ⭐ development fund 2023

#1056 [BUGFIX] Type must be string, null given in Classes/Controller/SearchController.php
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1057 [BUGFIX] Fix getOaiDocumentList()
  Classes/Controller/OaiPmhController.php
  Classes/Domain/Repository/DocumentRepository.php
Labels: 🐛 bug

#1062 [BUGFIX] Do not assume that return value from `Extbase\Persistence\Repository::findOneByRecordId` is not null
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1024 [BUGFIX] Make Toolbox render again
  Classes/Controller/ToolboxController.php
Labels: 🐛 bug

#1005 [FEATURE] Display ORDERLABEL as year in the search results if the structure type is year
  Resources/Private/Partials/ListView/Results.html
Labels: ⚙ feature

#1052 [MAINTENANCE] Introduce usage of PHPStan checks for new PR
  .github/phpstan.neon
  .github/workflows/phpstan.yml
  Classes/Api/Orcid/Client.php
  Classes/Api/Viaf/Client.php
  Classes/Command/BaseCommand.php
  Classes/Command/HarvestCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetadataInterface.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr/SearchResult/Highlight.php
  Classes/Common/Solr/Solr.php
  Classes/Common/Solr/SolrSearch.php
  Classes/Common/Solr/SolrSearchQuery.php
  Classes/Controller/AbstractController.php
  Classes/Controller/Backend/NewTenantController.php
  Classes/Controller/BasketController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/SearchController.php
  Classes/Domain/Model/Metadata.php
  Classes/Domain/Model/Structure.php
  Classes/Domain/Repository/CollectionRepository.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Classes/Format/AudioVideoMD.php
  Classes/Format/Mods.php
  Classes/Format/TeiHeader.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ItemsProcFunc.php
  Classes/Middleware/SearchInDocument.php
  Classes/Pagination/PageGridPagination.php
  Classes/Updates/FileLocationUpdater.php
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/FunctionalTestCase.php
  composer.json
Labels: 🛠 maintenance

#1063 [BUGFIX] Rename tool to tools in typoscript setup
  Configuration/TypoScript/Toolbox/setup.typoscript
Labels: 🐛 bug

#894 [MAINTENANCE] Added format unit tests.
  Tests/Fixtures/Format/alto.xml
  Tests/Fixtures/Format/altoNoString.xml
  Tests/Fixtures/Format/altoNoTextBlock.xml
  Tests/Fixtures/Format/altoNoTextLine.xml
  Tests/Fixtures/Format/audioVideo.xml
  Tests/Fixtures/Format/modsAuthorNoAutRoleTerm.xml
  Tests/Fixtures/Format/modsAuthorWithAutRoleTerm.xml
  Tests/Fixtures/Format/modsOriginInfo.xml
  Tests/Fixtures/Format/modsOriginInfoWithEditionElectronicEd.xml
  Tests/Unit/Format/AltoTest.php
  Tests/Unit/Format/AudioVideoMDTest.php
  Tests/Unit/Format/ModsTest.php
  Tests/Unit/Format/TeiHeaderTest.php
Labels: 🛠 maintenance, ⭐ development fund 2022

#895 [MAINTENANCE] Added additional repository functional test instead of unit tests.
  Tests/Fixtures/Repository/collections.xml
  Tests/Fixtures/Repository/mail.xml
  Tests/Fixtures/Repository/metadata.xml
  Tests/Fixtures/Repository/token.xml
  Tests/Functional/Repository/CollectionRepositoryTest.php
  Tests/Functional/Repository/MailRepositoryTest.php
  Tests/Functional/Repository/MetatdataRepositoryTest.php
  Tests/Functional/Repository/TokenRepositoryTest.php
Labels: 🛠 maintenance, ⭐ development fund 2022

#902 [MAINTENANCE] Add ViewHelper functional tests instead of unit tests.
  Tests/Functional/ViewHelpers/JsFooterViewHelperTest.php
  Tests/Functional/ViewHelpers/MetadataWrapVariableViewHelperTest.php
  Tests/Functional/ViewHelpers/StdWrapViewHelperTest.php
Labels: 🛠 maintenance, ⭐ development fund 2022

#919 [MAINTENANCE] Complete tests for MetsDocument
  Tests/Fixtures/MetsDocument/fulltext_0003.xml
  Tests/Fixtures/MetsDocument/mets_with_pages.xml
  Tests/Fixtures/MetsDocument/two_dmdsec.xml
  Tests/Functional/Common/MetsDocumentTest.php
Labels: 🛠 maintenance, ⭐ development fund 2022

#1066 [BUGFIX] Fix a typo in a condition, {{ insted of {
  Resources/Private/Partials/ListView/SortingForm.html
Labels: 🐛 bug

#1064 [MAINTENANCE] Convert database XML fixtures into CSV format
  Tests/Fixtures/Common/documents_1.csv
  Tests/Fixtures/Common/documents_1.xml
  Tests/Fixtures/Common/documents_fulltext.csv
  Tests/Fixtures/Common/documents_fulltext.xml
  Tests/Fixtures/Common/libraries.csv
  Tests/Fixtures/Common/libraries.xml
  Tests/Fixtures/Common/metadata.csv
  Tests/Fixtures/Common/metadata.xml
  Tests/Fixtures/MetsDocument/metadata_mets.csv
  Tests/Fixtures/MetsDocument/metadata_mets.xml
  Tests/Fixtures/OaiPmh/solrcores.csv
  Tests/Fixtures/OaiPmh/solrcores.xml
  Tests/Fixtures/Repository/collections.csv
  Tests/Fixtures/Repository/collections.xml
  Tests/Fixtures/Repository/mail.csv
  Tests/Fixtures/Repository/mail.xml
  Tests/Fixtures/Repository/metadata.csv
  Tests/Fixtures/Repository/metadata.xml
  Tests/Fixtures/Repository/token.csv
  Tests/Fixtures/Repository/token.xml
  Tests/Functional/Api/OaiPmhTest.php
  Tests/Functional/Common/HelperTest.php
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/Repository/CollectionRepositoryTest.php
  Tests/Functional/Repository/DocumentRepositoryTest.php
  Tests/Functional/Repository/MailRepositoryTest.php
  Tests/Functional/Repository/MetatdataRepositoryTest.php
  Tests/Functional/Repository/TokenRepositoryTest.php
Labels: 🛠 maintenance
