Repository kitodo/kitodo-presentation, pull requests merged in 2023-06, with the labels that each got.

#969 [BUGFIX] Revert #967 "Increase the amount of metadata loaded in collection view"
  Classes/Common/SolrSearch.php
Labels: 🐛 bug

#971 [BUGFIX] Fix error Illegal string offset 'id'
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#972 [BUGFIX] Check for getDoc equal null in DocumentTypeFunctionProvider
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#973 [BUGFIX] Check if result returned from suggester is iterable before passing it to the array
  Classes/Eid/SearchSuggest.php
Labels: 🐛 bug

#957 [BUGFIX] Display volumes correctly in ToC plugin
  Classes/Command/BaseCommand.php
  Classes/Controller/TableOfContentsController.php
Labels: 🐛 bug

#975 [MAINTENANCE] Adjust deprecated calls for database queries
  Classes/Command/BaseCommand.php
  Classes/Common/Doc.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/Solr.php
  Classes/Controller/OaiPmhController.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Hooks/DataHandler.php
  Classes/Updates/FileLocationUpdater.php
  Classes/Updates/MigrateSettings.php
Labels: 🛠 maintenance

#948 [FEATURE] Add more search operators and fix highlighting
  Classes/Common/Solr.php
  Classes/Common/SolrSearch.php
  Classes/Controller/SearchController.php
  Resources/Public/JavaScript/PageView/PageView.js
Labels: ⚙ feature

#970 [FEATURE] Make amount of children rows configurable
  Classes/Common/SolrSearch.php
  Documentation/Plugins/Index.rst
Labels: ⚙ feature

#976 [MAINTENANCE] Remove unused imports and declarations
  Classes/Command/HarvestCommand.php
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
  Classes/Common/Doc.php
  Classes/Common/Indexer.php
  Classes/Common/Solr.php
  Classes/Common/SolrSearch.php
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/Backend/NewTenantController.php
  Classes/Controller/BasketController.php
  Classes/Controller/CalendarController.php
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/SearchController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/View3DController.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Eid/SearchSuggest.php
  Classes/Hooks/DataHandler.php
Labels: 🛠 maintenance

#977 [MAINTENANCE] Improve readability in SearchController
  Classes/Controller/SearchController.php
  Classes/Domain/Repository/DocumentRepository.php
Labels: 🛠 maintenance

#978 [BUGFIX] Fix SolrSearch implementation
  Classes/Common/SolrSearch.php
Labels: 🐛 bug

#979 [BUGFIX] Fixes in Doc class
  Classes/Common/Doc.php
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#980 [BUGFIX] Fix logger docs in API classes
  Classes/Api/Orcid/Client.php
  Classes/Api/Orcid/Profile.php
  Classes/Api/Viaf/Client.php
  Classes/Api/Viaf/Profile.php
Labels: 🐛 bug
