Repository kitodo/kitodo-presentation, pull requests merged in 2023-11, with the labels that each got.

#1065 [MAINTENANCE] Additional fixes in the test classes
  Tests/Functional/Api/OaiPmhTest.php
  Tests/Functional/Api/PageViewProxyDisabledTest.php
  Tests/Functional/Api/PageViewProxyTest.php
  Tests/Functional/Common/HelperTest.php
  Tests/Functional/Common/IiifUrlReaderTest.php
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/FunctionalTestCase.php
  Tests/Functional/Repository/CollectionRepositoryTest.php
  Tests/Functional/Repository/DocumentRepositoryTest.php
  Tests/Functional/Repository/MailRepositoryTest.php
  Tests/Functional/Repository/MetatdataRepositoryTest.php
  Tests/Functional/Repository/TokenRepositoryTest.php
  Tests/Functional/ViewHelpers/MetadataWrapVariableViewHelperTest.php
  Tests/Functional/ViewHelpers/StdWrapViewHelperTest.php
  Tests/Unit/Common/HelperTest.php
  Tests/Unit/Format/AltoTest.php
  Tests/Unit/Format/AudioVideoMDTest.php
  Tests/Unit/Format/ModsTest.php
Labels: 🛠 maintenance

#1067 [BUGFIX] Fix call to extension configuration
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1068 [BUGFIX] Remove assignment of nonexistent $widgetPage
  Classes/Controller/ListViewController.php
Labels: 🐛 bug

#1070 [BUGFIX] Cast `$min` and `$max` to int in CalendarController
  Classes/Controller/CalendarController.php
Labels: 🐛 bug

#1071 [BUGFIX] Move assignment of `storagePid` into try block to avoid undefined error
  Classes/Hooks/ItemsProcFunc.php
Labels: 🐛 bug

#1072 [BUGFIX] Define `$scheme` to avoid undefined warning
  Classes/Controller/MetadataController.php
Labels: 🐛 bug

#1073 [BUGFIX] Remove second `if` checking the same condition
  Classes/Controller/NavigationController.php
Labels: 🐛 bug

#1074 [BUGFIX] Make `useOriginalIiifManifestMetadata` class parameter
  Classes/Controller/MetadataController.php
Labels: 🐛 bug

#1081 [MAINTENANCE] Rename getTitledata to getToplevelMetadata
  Classes/Command/BaseCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/MetsDocument.php
  Classes/Controller/CalendarController.php
  Classes/Controller/MetadataController.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Tests/Functional/Common/MetsDocumentTest.php
Labels: 🛠 maintenance

#1083 [MAINTENANCE] Split code in calendarAction into own functions
  Classes/Controller/CalendarController.php
Labels: 🛠 maintenance

#1080 [BUGFIX] DataHandler: Change uid type from `int` to `string`
  Classes/Hooks/DataHandler.php
Labels: 🐛 bug

#1076 [BUGFIX] Fix missing pagination between first and last page
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug

#1085 [BUGFIX] Fix for "Typed property AbstractController::$document must not be accessed before initialization"
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1086 [BUGFIX] Remove double check for not null on `$document` property
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1079 [MAINTENANCE] Reorder keywords and abstract functions in AbstractDocument class
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1088 [BUGFIX] Fix search middleware to use right method
  Classes/Middleware/SearchInDocument.php
  Classes/Middleware/SearchSuggest.php
Labels: 🐛 bug

#1087 [BUGFIX] Use paginator in 'SearchController.php' and 'CollectionController.php'
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1091 [BUGFIX] The function `errorAction()` needs to exists in `NewTenantController`
  Classes/Controller/Backend/NewTenantController.php
Labels: 🐛 bug

#1097 [BUGFIX] Fix calls to `ExtensionUtility::configurePlugin`
  ext_localconf.php
Labels: 🐛 bug

#1090 [FEATURE] Enhance fulltext retrieval on virtual collections by providing database independent identifier
  Classes/Common/Indexer.php
Labels: ⚙ feature
