Repository kitodo/kitodo-presentation, pull requests merged in 2023-02, with the labels that each got.

#896 [MAINTENANCE] Change variable type to match parameter in collection testrun
  Tests/Functional/Common/SolrIndexingTest.php
Labels: maintenance

#874 [BUGFIX] Fix virtual and normal collections
  Classes/Common/SolrSearch.php
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
  Resources/Private/Partials/ListView/SortingForm.html
  Resources/Private/Templates/Search/Main.html
Labels: bug

#898 [MAINTENANCE] Update OpenLayers from 6.12.0 to 7.2.2
  Resources/Public/Javascript/OpenLayers/get-ol.sh
  Resources/Public/Javascript/OpenLayers/openlayers.css
  Resources/Public/Javascript/OpenLayers/openlayers.js
Labels: maintenance

#899 [MAINTENANCE] Simplify and unify check for doc existence
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/BasketController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Classes/Controller/View3DController.php
Labels: bug, maintenance

#901 [FEATURE] Add an option to list empty years in calender plugin
  Classes/Controller/CalendarController.php
  Configuration/Flexforms/Calendar.xml
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Templates/Calendar/Years.html
Labels: feature

#903 [MAINTENANCE] Basket: Typo3 10.x context api
  Classes/Controller/BasketController.php
Labels: maintenance

#906 [MAINTENANCE] Move add Dublic Core data to separated method
  Classes/Controller/OaiPmhController.php
Labels: maintenance

#912 [MAINTENANCE] Add 'SameSite' attribute to cookies
  Resources/Public/JavaScript/PageView/AnnotationControl.js
  Resources/Public/JavaScript/PageView/FulltextControl.js
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: bug

#911 [MAINTENANCE] Read SOLR fields only once from config
  Classes/Common/Solr.php
Labels: maintenance

#913 [BUG] Fix return in void method
  Classes/Controller/SearchController.php
Labels: bug

#907 [MAINTENANCE] Fix OaiPmh functional tests
  Tests/Functional/Api/OaiPmhTest.php
  Tests/Functional/FunctionalTestCase.php
Labels: bug, maintenance

#914 [BUGFIX] Fix SinglepageOn and Off and hint if numPages not > 0
  Resources/Private/Templates/Navigation/Main.html
Labels: bug
