Repository kitodo/kitodo-presentation, pull requests merged in 2023-07, with the labels that each got.

#983 [BUGFIX] Persist collection to prevent duplicates
  Classes/Command/BaseCommand.php
Labels: 🐛 bug

#984 [FEATURE] Use order in case volume_sorting is empty
  Classes/Command/BaseCommand.php
Labels: ⚙ feature

#986 [BUGFIX] Fix return type for getTableOfContentsFromDb function
  Classes/Controller/TableOfContentsController.php
  Classes/Domain/Repository/DocumentRepository.php
Labels: 🐛 bug

#982 [MAINTENANCE] Fix and move Solr classes
  Classes/Common/Indexer.php
  Classes/Common/Solr/SearchResult/Highlight.php
  Classes/Common/Solr/SearchResult/Page.php
  Classes/Common/Solr/SearchResult/Region.php
  Classes/Common/Solr/SearchResult/ResultDocument.php
  Classes/Common/Solr/Solr.php
  Classes/Common/Solr/SolrSearch.php
  Classes/Common/Solr/SolrSearchQuery.php
  Classes/Controller/Backend/NewTenantController.php
  Classes/Controller/CollectionController.php
  Classes/Controller/OaiPmhController.php
  Classes/Controller/SearchController.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Eid/SearchInDocument.php
  Classes/Eid/SearchSuggest.php
  Classes/Hooks/ConfigurationForm.php
  Classes/Hooks/DataHandler.php
  Classes/Hooks/Form/FieldInformation/SolrCoreStatus.php
  Tests/Functional/Api/OaiPmhTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/FunctionalTestCase.php
Labels: 🐛 bug, 🛠 maintenance

#989 [BUGFIX] Use $forceReload parameter in getInstance
  Classes/Common/Doc.php
Labels: 🐛 bug

#991 [BUGFIX] Remove not needed call to createDocument function
  Classes/Common/Indexer.php
Labels: 🐛 bug

#992 [BUGFIX] Minor fixes in Helper class
  Classes/Common/Helper.php
Labels: 🐛 bug

#993 [BUGFIX] Minor fixes in ToolboxController
  Classes/Controller/ToolboxController.php
Labels: 🐛 bug
