Repository kitodo/kitodo-presentation, pull requests merged in 2024-12, with the labels that each got.

#1377 [BUGFIX] Fix highlighting for words
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🐛 bug

#1397 [BUGFIX] Fix highlighting for words 5.x
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🐛 bug

#1378 [BUGFIX] Fix return and var tags in PHPDocs
  Classes/Common/Solr/SearchResult/ResultDocument.php
  Classes/Common/Solr/Solr.php
Labels: 🐛 bug

#1379 [BUGFIX] Fix `getStructureDepth()` to match its documentation
  Classes/Common/MetsDocument.php
  Tests/Functional/Common/MetsDocumentTest.php
Labels: 🐛 bug

#1382 [BUGFIX] Fix displaying count of documents
  Classes/Domain/Repository/DocumentRepository.php
Labels: 🐛 bug

#1383 [BUGFIX] Adjust null checks so they also check for non existent key arrays
  Classes/Command/BaseCommand.php
Labels: 🐛 bug

#1384 [BUGFIX] Reverse sort the keys in JSON array
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1386 [BUGFIX] Define `$entry` variable
  Classes/Controller/PageGridController.php
Labels: 🐛 bug

#1387 [BUGFIX] Improve score loading condition in PageView.js
  Resources/Public/JavaScript/PageView/PageView.js
Labels: 🐛 bug

#1388 [BUGFIX] Remove redundant call to `array_values()`
  Classes/Domain/Repository/CollectionRepository.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Domain/Repository/MetadataRepository.php
  Classes/Domain/Repository/TokenRepository.php
Labels: 🐛 bug

#1389 [MAINTENANCE] Remove unused function `getCollectionForMetadata()`
  Classes/Domain/Repository/CollectionRepository.php
  Tests/Functional/Repository/CollectionRepositoryTest.php
Labels: 🛠 maintenance

#1398 [BUGFIX] Fix GEO JSON in 4.x
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1399 [BUGFIX] Fix GEO JSON in 5.x
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1396 [BUGFIX] Fix collection search
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1400 [BUGFIX] Fix displaying document count in statistics in 5.x
  Classes/Domain/Repository/DocumentRepository.php
Labels: 🐛 bug

#1401 [FEATURE] Implement document cache manager
  Classes/Command/ReindexCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/DocumentCacheManager.php
Labels: ⚙ feature

#1403 [MAINTENANCE] Extract load of IIIF resource to protected function
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1402 [FEATURE] Implement full text reader
  Classes/Common/AbstractDocument.php
  Classes/Common/FullTextReader.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: ⚙ feature

#1394 [FEATURE] Implement IntlDateFormatter for SolrCoreStatus timestamps
  Classes/Hooks/Form/FieldInformation/SolrCoreStatus.php
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/locallang_be.xlf
Labels: ⚙ feature

#1405 [BUGFIX] Use the document cache in `getDocumentByUid()`
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1409 [MAINTENANCE] Add function for getting index annotations
  Classes/Common/IiifManifest.php
Labels: 🛠 maintenance

#1412 [MAINTENANCE] Remove paramater from the magic get function
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1413 [MAINTENANCE] Don't use file conf as function parameter
  Classes/Controller/PageGridController.php
Labels: 🛠 maintenance

#1414 [MAINTENANCE] Move set up of fulltext to correct function
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1415 [MAINTENANCE] Simplify attributes' reading
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1417 [BUGFIX] Fix regression for METS files without physical structure
  Classes/Common/MetsDocument.php
  Classes/Controller/CalendarController.php
  Classes/Controller/MetadataController.php
Labels: 🐛 bug
