Repository kitodo/kitodo-presentation, pull requests merged in 2024-07, with the labels that each got.

#1255 [MAINTENANCE] Simplify usage of metadata sections
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1256 [MAINTENANCE] Adjust variable names to match naming standards
  Classes/Command/HarvestCommand.php
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
Labels: 🛠 maintenance

#1257 [MAINTENANCE] Get encryption key using configuration manager instead of global access
  Classes/Common/Helper.php
Labels: 🛠 maintenance

#1258 [MAINTENANCE] Get options for hooks from local configuration instead of global access
  Classes/Common/Helper.php
  Tests/Functional/FunctionalTestCase.php
Labels: 🛠 maintenance

#1260 [MAINTENANCE] Remove unused functions from `Helper` class
  Classes/Common/Helper.php
Labels: 🛠 maintenance

#1262 [BUGFIX] Fix params array for searching collections
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1263 [BUGFIX] Fix `getEntry()` function in `BasketController`
  Classes/Controller/BasketController.php
Labels: 🐛 bug

#1265 [MAINTENANCE] Increase code readability in TableOfContents controller
  Classes/Controller/TableOfContentsController.php
Labels: 🛠 maintenance

#1266 [MAINTENANCE] Adjustments and minor fixes in Hooks
  Classes/Hooks/DataHandler.php
  Classes/Hooks/ItemsProcFunc.php
  Classes/Hooks/KitodoProductionHacks.php
Labels: 🛠 maintenance

#1267 [MAINTENANCE] Split `magicGetPhysicalStructure()` function to increase readability
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#910 [FEATURE] Two-level metadata: Model and appearance
  .gitignore
  Classes/Common/Helper.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Controller/MetadataController.php
  Classes/Domain/Model/MetadataFormat.php
  Classes/Domain/Model/MetadataSubentry.php
  Classes/Domain/Repository/MetadataSubentryRepository.php
  Classes/Hooks/DataHandler.php
  Classes/ViewHelpers/IsArrayViewHelper.php
  Configuration/Extbase/Persistence/Classes.php
  Configuration/TCA/tx_dlf_metadataformat.php
  Configuration/TCA/tx_dlf_metadatasubentries.php
  Resources/Private/Partials/Metadata/Entries.html
  ext_tables.sql
  ext_typoscript_setup.txt
Labels: ⚙ feature

#1248 [BUGFIX] Fix SearchInDocument middleware
  Classes/Common/Solr/SearchResult/Region.php
  Classes/Common/Solr/SearchResult/ResultDocument.php
  Classes/Controller/ToolboxController.php
  Classes/Middleware/SearchInDocument.php
  Resources/Private/Templates/Toolbox/Main.html
Labels: 🐛 bug

#1270 [BUGFIX] Fix 'Undefined array key `fulltext`' in `SolrSearch`
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1271 [BUGFIX] Add $field to the facetset otherwise the name of the field does not exist
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1274 [BUGFIX] Add fallback for `SC_OPTIONS` for case when it is defined in `ext_localconf.php`
  Classes/Common/Helper.php
Labels: 🐛 bug

#1119 [FEATURE] Scheduler tasks for indexing, reindexing and harvesting of documents
  Classes/Command/IndexCommand.php
  Classes/Task/BaseAdditionalFieldProvider.php
  Classes/Task/BaseTask.php
  Classes/Task/HarvestAdditionalFieldProvider.php
  Classes/Task/HarvestTask.php
  Classes/Task/IndexAdditionalFieldProvider.php
  Classes/Task/IndexTask.php
  Classes/Task/ReindexAdditionalFieldProvider.php
  Classes/Task/ReindexTask.php
  Resources/Private/Language/de.locallang_tasks.xlf
  Resources/Private/Language/locallang_tasks.xlf
  composer.json
  ext_localconf.php
Labels: ⚙ feature, ⭐ development fund 2023

#1259 [FEATURE] 3D viewers integration
  Classes/Controller/AbstractController.php
  Classes/Controller/View3DController.php
  Classes/Format/Mods.php
  Classes/Middleware/Embedded3DViewer.php
  Configuration/RequestMiddlewares.php
  Configuration/TypoScript/setup.typoscript
  Documentation/Developers/3DViewer.rst
  Documentation/Developers/Index.rst
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_labels.xlf
  Resources/Private/Templates/View3D/Main.html
  Resources/Private/Templates/View3D/Standalone.html
  Resources/Public/JavaScript/3DViewer/img/cloud-arrow-down.svg
  Resources/Public/JavaScript/3DViewer/img/fullscreen.png
  Resources/Public/JavaScript/3DViewer/img/share.svg
  Resources/Public/JavaScript/3DViewer/main.js
  Resources/Public/JavaScript/3DViewer/model-viewer-3.5.0.min.js
  Resources/Public/Stylesheets/3d-viewer.css
  ext_conf_template.txt
Labels: ⚙ feature

#1283 [IMPROVEMENT] Improvements 3d viewer implementation
  Classes/Controller/AbstractController.php
  Classes/Controller/Embedded3dViewerController.php
  Classes/Controller/View3DController.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Classes/Middleware/Embedded3dViewer.php
  Configuration/FlexForms/Embedded3dViewer.xml
  Configuration/FlexForms/View3D.xml
  Configuration/RequestMiddlewares.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TsConfig/ContentElements.tsconfig
  Configuration/TypoScript/setup.typoscript
  Documentation/Developers/Embedded3DViewer.rst
  Documentation/Developers/Index.rst
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Language/locallang_labels.xlf
  Resources/Private/Templates/Embedded3dViewer/Main.html
  Resources/Private/Templates/Embedded3dViewer/Standalone.html
  Resources/Public/Icons/tx-dlf-embedded3dviewer.svg
  Resources/Public/JavaScript/Embedded3dViewer/model-viewer-3.5.0.min.js
  Resources/Public/Stylesheets/3d-viewer.css
  Resources/Public/Stylesheets/embedded-3d-viewer.css
  ext_conf_template.txt
  ext_localconf.php
Labels: ⚙ feature

#1288 [BUGFIX] Fix syntax errors and remove redundant closing tag in navigation template
  Resources/Private/Templates/Navigation/Main.html
Labels: 🐛 bug

#1289 [FEATURE] Use Solr suggester component for search hints
  Classes/Command/IndexCommand.php
  Classes/Command/SuggestBuildCommand.php
  Classes/Common/Solr/Solr.php
  Classes/Middleware/SearchSuggest.php
  Classes/Task/BaseAdditionalFieldProvider.php
  Classes/Task/SuggestBuildAdditionalFieldProvider.php
  Classes/Task/SuggestBuildTask.php
  Configuration/ApacheSolr/configsets/dlf/conf/schema.xml
  Configuration/ApacheSolr/configsets/dlf/conf/solrconfig.xml
  Configuration/ApacheSolr/configsets/dlf/conf/solrconfig_8.11.2.xml
  Configuration/Services.yaml
  Resources/Private/Language/de.locallang_tasks.xlf
  Resources/Private/Language/locallang_tasks.xlf
  ext_localconf.php
Labels: ⚙ feature, ⭐ development fund 2023
