Repository kitodo/kitodo-presentation, pull requests merged in 2024-10, with the labels that each got.

#1351 [MAINTENANCE] Fix braces in `Client` classes
  Classes/Api/Orcid/Client.php
  Classes/Api/Viaf/Client.php
Labels: 🛠 maintenance

#1349 [MAINTENANCE] Update version in `ext_emconf.php`
  ext_emconf.php
Labels: 🛠 maintenance

#1353 [MAINTENANCE] Improve reading of file groups
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1344 [BUGFIX] Fix exception when showing metadata of a document
  Classes/Controller/MetadataController.php
Labels: 🐛 bug

#1345 [BUGFIX] Fix for `$documentArray` being `null` after function `getDocumentById` is called
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1346 [BUGFIX] Setup `pageStep` if FlexForm is not working
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1347 [BUGFIX] Fix errors caused by missing keys in entry array
  Classes/Controller/TableOfContentsController.php
Labels: 🐛 bug

#1104 [MAINTENANCE] Adjust language field in TCA
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_libraries.php
  Configuration/TCA/tx_dlf_metadata.php
  Configuration/TCA/tx_dlf_structures.php
Labels: 🛠 maintenance

#1338 [FEATURE] Implement MIME type filtering for files in Helper class
  Classes/Common/Helper.php
  Classes/Controller/PageViewController.php
  Classes/Controller/ToolboxController.php
Labels: ⚙ feature

#1355 [DOCUMENTATION] Deploy documentation to GitHub Pages
  .github/workflows/documentation.yml
Labels: ⚙ feature, 📖 documentation

#1357 [MAINTENANCE] Organize plugins in `tt_content.php` file
  Configuration/TCA/Overrides/tt_content.php
Labels: 🛠 maintenance

#1356 [BUGFIX] Iterate over metadata ids only if there are any metadata sections
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1358 [BUGFIX] Fix logger for score file groups
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1359 [BUGFIX] ExpressionLanguage function `getDocumentType` of `DocumentTypeFunctionProvider` does not work correctly
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#1360 [MAINTENANCE] Fix some typos in configuration, documentation and code comments
  Classes/Common/MetsDocument.php
  Classes/Controller/AbstractController.php
  Classes/Task/BaseTask.php
  Configuration/Services.yaml
  Documentation/Developers/Embedded3DViewer.rst
Labels: 🛠 maintenance, 📖 documentation

#1362 [MAINTENANCE] Cleanup and improvements regarding TYPO3 12 update
  .gitignore
  Build/Documentation/.gitignore
  Build/Documentation/conf.py
  Build/Documentation/dbdocs/Generator.php
  Build/Documentation/sphinx.sh
  Classes/Common/MetsDocument.php
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/MetadataController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Resources/Private/Partials/Lists/Pagination.html
  Resources/Private/Templates/Feeds/Main.xml
Labels: 🛠 maintenance

#1363 [BUGFIX] Fix exception 'data structure identifier must be set'
  Configuration/TCA/Overrides/tt_content.php
Labels: 🐛 bug

#1364 [MAINTENANCE] Fix Typo3 v11 TCA migration warning 89672
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_libraries.php
  Configuration/TCA/tx_dlf_metadata.php
  Configuration/TCA/tx_dlf_structures.php
Labels: 🛠 maintenance
