Repository kitodo/kitodo-presentation, pull requests merged in 2024-11, with the labels that each got.

#1368 [MAINTENANCE] Improvements regarding TYPO3 12 update
  .github/workflows/phpstan.yml
  Classes/Controller/AbstractController.php
  Classes/Controller/TableOfContentsController.php
  Classes/Controller/ToolboxController.php
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
  Classes/Middleware/Embedded3dViewer.php
  Configuration/TypoScript/setup.typoscript
  Resources/Public/Html/Embedded3dViewerStandalone.html
  Resources/Public/JavaScript/WildWebMidi/wildwebmidi.js
Labels: 🛠 maintenance

#1369 [FEATURE] Update schema using Solr Schema API
  Classes/Updates/UpdateSolrSchema.php
  Documentation/Administrator/Index.rst
  ext_localconf.php
Labels: ⚙ feature, ⭐ development fund 2023

#1370 [SECURITY] Update Symfony components to mitigate security issues
  composer.lock
Labels: ⚡ security

#1371 [SECURITY] Update Symfony components to mitigate security issues
  composer.lock
Labels: ⚡ security

#1372 [BUGFIX] Fix passing page id in `ToolboxController`
  Classes/Controller/ToolboxController.php
  Resources/Private/Templates/Toolbox/Main.html
Labels: 🐛 bug
