Repository kitodo/kitodo-presentation, pull requests merged in 2024-05, with the labels that each got.

#1190 [BUGFIX] Check if `$this->documentRepository` is set
  Classes/Hooks/DataHandler.php
Labels: 🐛 bug

#1192 [BUGFIX] Fix `NULL` exception for empty `title_sorting`
  Classes/Command/BaseCommand.php
Labels: 🐛 bug

#1193 [BUGFIX] Fix saving to database for documents with many authors
  Classes/Command/BaseCommand.php
Labels: 🐛 bug

#1117 [FEATURE] Add support for ALTO v3 and v4
  Classes/Format/Alto.php
Labels: ⚙ feature

#1195 [MAINTENANCE] Refactor metadata extraction
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1196 [MAINTENANCE] Replace registry with cache
  Classes/Command/ReindexCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1197 [MAINTENANCE] Clear state of persistence manager to avoid memory exhaustion
  Classes/Command/BaseCommand.php
  Classes/Command/ReindexCommand.php
Labels: 🛠 maintenance

#1200 [MAINTENANCE] Use intermediate variables to decrease accessing the array
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1198 [MAINTENANCE] Remove unnecessary casts `$cPid` to `int`
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1199 [MAINTENANCE] Remove unnecessary parentheses
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1203 [BUGFIX] Rename reindex options to be able use one letter shorts
  Classes/Command/ReindexCommand.php
  Documentation/User/Index.rst
Labels: 🐛 bug

#1202 [BUGFIX] Clear state of the persistence memory after given chunk of data was indexed
  Classes/Command/ReindexCommand.php
Labels: 🐛 bug

#1204 [BUGFIX] fix incomplete renaming reindexing option "index-start" to "index-begin"
  Classes/Command/ReindexCommand.php
Labels: 🐛 bug

#1207 [MAINTENANCE] Replace `chr(31)` with `pack('C', 31)`
  Classes/Command/BaseCommand.php
  Classes/Common/Indexer.php
  Classes/Format/Mods.php
Labels: 🛠 maintenance

#1186 [BUGFIX] Add `languageUid` to `index_name` to make it unique
  Classes/Controller/Backend/NewTenantController.php
Labels: 🐛 bug

#1184 [BUGFIX] Add `sorting` key to metadata
  Classes/Controller/Backend/NewTenantController.php
  Resources/Private/Data/MetadataDefaults.php
Labels: 🐛 bug

#1172 [MAINTENANCE] Add support for PHP 8.3.x
  Build/Test/docker-compose.yml
  Build/Test/runTests.sh
  Classes/Common/Solr/Solr.php
  composer.json
Labels: 🛠 maintenance

#1210 Prepare Release 5.0
  Documentation/Administrator/Index.rst
  Documentation/Community/Index.rst
  README.md
  composer.json
  composer.lock
  composer.lock-t3v10
Labels: 🛠 maintenance

#1211 [BUGFIX] Add `languageUid` to `index_name` to make it unique for structures too
  Classes/Controller/Backend/NewTenantController.php
Labels: 🐛 bug

#1214 [BUGFIX] Fix versions in `ext_emconf.php`
  ext_emconf.php
Labels: 🐛 bug

#1213 [MAINTENANCE] Replace Sphinx with new Typo3 documentation variant
  .github/workflows/documentation.yml
  DEVELOPMENT.md
  Documentation/Configuration/Index.rst
  Documentation/Developers/Metadata.rst
  Documentation/Images/AdministratorManual/ExtensionManager.png
  Documentation/Images/Configuration/New_TYPO3_site.png
  Documentation/Images/Introduction/Digitale_Sammlungen_Colloquia_Lutheri.png
  Documentation/Images/Introduction/Digitale_Sammlungen_Dresdner_Nachrichten.png
  Documentation/Images/Introduction/Digitale_Sammlungen_Dresdner_Nachrichten_1942.png
  Documentation/Images/Introduction/Digitale_Sammlungen_The_Daily_1906.png
  Documentation/Introduction/Index.rst
  Documentation/Plugins/Index.rst
  Documentation/Settings.cfg
  Documentation/User/Index.rst
  Documentation/guides.xml
  composer.json
Labels: 🛠 maintenance, 📖 documentation

#1216 [BUGFIX] Fix cache assignment in `ext_localconf.php` for arrays
  ext_localconf.php
Labels: 🐛 bug

#1150 [MAINTENANCE] Use nested extension configuration
  Classes/Command/BaseCommand.php
  Classes/Common/AbstractDocument.php
  Classes/Common/Helper.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Common/Solr/Solr.php
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/ToolboxController.php
  Classes/Eid/PageViewProxy.php
  Classes/Hooks/DataHandler.php
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_labels.xlf
  Tests/Functional/Api/PageViewProxyTest.php
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/FunctionalTestCase.php
  ext_conf_template.txt
  ext_localconf.php
Labels: 🛠 maintenance

#1194 [FEATURE] Use MODS reader library
  Classes/Format/Mods.php
  composer.json
Labels: ⚙ feature

#1218 [MAINTENANCE] Run workflows on 5.x branch
  .github/workflows/codeql.yml
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
Labels: 🛠 maintenance

#1149 [FEATURE] Implement document validation before document is saved to database
  Classes/Command/BaseCommand.php
  Classes/Command/IndexCommand.php
  Classes/Validation/DocumentValidator.php
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_labels.xlf
  Tests/Unit/Validation/DocumentValidatorTest.php
  ext_conf_template.txt
Labels: ⚙ feature

#1158 [FEATURE] Implement document validation before document is saved to SOLR
  Classes/Command/IndexCommand.php
  Classes/Common/Indexer.php
  Tests/Functional/FunctionalTestCase.php
Labels: ⚙ feature

#1219 [BUGFIX] Fix assignment of `storagePid` and streamline `initializeRepositories` in `BaseCommand`
  Classes/Command/BaseCommand.php
  Classes/Command/DeleteCommand.php
  Classes/Command/HarvestCommand.php
  Classes/Command/IndexCommand.php
  Classes/Command/ReindexCommand.php
Labels: 🐛 bug

#1223 [MAINTENANCE] Adjust compability with PHP 8 for XML loading
  Classes/Common/Helper.php
Labels: 🛠 maintenance

#1221 [BUGFIX] Return in `SearchController` if no search parameters exist
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1222 [BUGFIX] Fix access to non existent key in array
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1225 [BUGFIX] Assign snippets only if they exists for given id
  Classes/Common/Solr/SearchResult/ResultDocument.php
Labels: 🐛 bug

#1226 [BUGFIX] Fix warning for undefined array key page
  Classes/Controller/ListViewController.php
  Classes/Controller/PageGridController.php
Labels: 🐛 bug

#1227 [BUGFIX] Fix warnings for undefined array keys in `Mods` class
  Classes/Format/Mods.php
Labels: 🐛 bug

#1228 [BUGFIX] Fix warnings for undefined keys in `$settings` array
  Classes/Domain/Repository/MetadataRepository.php
Labels: 🐛 bug

#1229 [BUGFIX] Return null in case when there is no file info for id
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1230 [BUGFIX] Fix usage of `$this->settings['basketButton']`
  Classes/Controller/TableOfContentsController.php
Labels: 🐛 bug

#1231 [BUGFIX] Set fulltext as false if there is no element for fulltext index
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1232 [BUGFIX] Assign document only if there is document for given id
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1233 [BUGFIX] Safely get the next and previous page numbers
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1234 [BUGFIX] Check if core exists in registry array
  Classes/Common/Solr/Solr.php
Labels: 🐛 bug

#1235 [BUGFIX] Fix checking if file group exists
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1237 [BUGFIX] Fix check if fulltext file group exists in `ToolboxController`
  Classes/Controller/ToolboxController.php
Labels: 🐛 bug

#1238 [BUGFIX] Fix reading `storagePid` from `settings` array
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1240 [BUGFIX] Adjust reindexing command in given range
  Classes/Command/ReindexCommand.php
  Classes/Domain/Repository/DocumentRepository.php
  Documentation/User/Index.rst
Labels: 🐛 bug

#1239 [BUGFIX] Fix configuration for `forceAbsoluteUrl` property
  Classes/Controller/AbstractController.php
  Classes/Controller/PageViewController.php
  Resources/Private/Language/locallang_labels.xlf
Labels: 🐛 bug

#1241 [BUGFIX] Correctly check if `storagePid` key exists in array
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1236 [BUGFIX] Use empty array if wrap for given property doesn't exists
  Classes/ViewHelpers/MetadataWrapVariableViewHelper.php
Labels: 🐛 bug

#1242 [RELEASE] Kitodo.Presentation 5.0.1
  ext_emconf.php
Labels: 🛠 maintenance
