Repository kitodo/kitodo-presentation, pull requests merged in 2024-02, with the labels that each got.

#1160 [MAINTENANCE] Minor improvements in Helper class
  Classes/Common/Helper.php
Labels: 🛠 maintenance

#1161 [MAINTENANCE] Minor improvements in IiifManifest class
  Classes/Common/IiifManifest.php
Labels: 🛠 maintenance

#1162 [MAINTENANCE] Minor improvements in MetsDocument class
  Classes/Common/MetsDocument.php
Labels: 🛠 maintenance

#1164 [MAINTENANCE] Document function magicGetMetadataArray as a "magic" function
  Classes/Common/AbstractDocument.php
Labels: 🛠 maintenance

#1166 [MAINTENANCE] Replace calls of function sizeof by calls of function count
  Classes/Controller/BasketController.php
  Classes/Controller/ToolboxController.php
Labels: 🛠 maintenance

#1170 [BUGFIX] Add missing translations for metadata
  Resources/Private/Language/de.locallang_metadata.xlf
  Resources/Private/Language/locallang_metadata.xlf
Labels: 🐛 bug

#1171 [MAINTENANCE] Suppress Codacy warnings for private methods...
  Classes/Controller/ToolboxController.php
Labels: 🛠 maintenance

#1175 [SECURITY] Update dependencies to fix security issues (4.x branch)
  .github/workflows/codacy.yml.disabled
  .github/workflows/codeql.yml
  .github/workflows/tests.yml
  README.md
  composer.json
  composer.lock
Labels: 🛠 maintenance, ⚡ security

#1169 [BUGFIX] Fix problems with translation of database records
  Configuration/TCA/tx_dlf_basket.php
  Configuration/TCA/tx_dlf_collections.php
  Configuration/TCA/tx_dlf_libraries.php
  Configuration/TCA/tx_dlf_metadata.php
  Configuration/TCA/tx_dlf_structures.php
  ext_tables.sql
Labels: 🐛 bug

#1179 [BUGFIX] Add missing fields to to metadata format table
  Configuration/TCA/tx_dlf_metadataformat.php
  Tests/Fixtures/Common/metadata.csv
  Tests/Fixtures/MetsDocument/metadata_mets.csv
  Tests/Fixtures/Repository/metadata.csv
  ext_tables.sql
Labels: 🐛 bug

#1103 [BUGFIX] Show only specific range of pages in pagination, add "..."
  Classes/Controller/AbstractController.php
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug

#1159 [MAINTENANCE] Minor improvements in test classes
  Tests/Functional/Common/SolrSearchQueryTest.php
  Tests/Functional/Common/SolrSearchTest.php
  Tests/Functional/Common/SolrTest.php
  Tests/Functional/FunctionalTestCase.php
Labels: 🛠 maintenance

#1180 [MAINTENANCE] Update path for Docker images to work also with podman
  Build/Documentation/docker-compose.t3docs.yml
  Build/Test/docker-compose.yml
Labels: 🛠 maintenance

#931 [BUGFIX] Fix wrong sorting of volumes in listview and toc
  Classes/Domain/Repository/DocumentRepository.php
Labels: 🐛 bug
