Repository kitodo/kitodo-presentation, pull requests merged in 2025-04, with the labels that each got.

#1561 [BUGFIX] Fix some issues reported by PHPStan (nullable function parameters)
  Classes/Common/Solr/SolrSearch.php
  Classes/Controller/NavigationController.php
  Classes/Task/BaseAdditionalFieldProvider.php
  Classes/Validation/AbstractDlfValidationStack.php
Labels: 🐛 bug

#1562 [BUGFIX] Update documentation for AbstractController::loadDocument
  Classes/Controller/AbstractController.php
  Classes/Controller/BasketController.php
Labels: 🐛 bug

#1564 [BUGFIX] Fix adding empty xpath results to metadata array
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1526 [BUGFIX] Rewrite `CollectionController`, `ListViewController` and `SearchController`
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1527 [BUGFIX] Rewrite `CollectionController`, `ListViewController` and `SearchController`
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1557 [BUGFIX] Fix displaying for missing title
  Classes/Common/SolrPaginator.php
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Resources/Private/Partials/ListView/SearchHits.html
  Resources/Private/Templates/ListView/Main.html
  Resources/Private/Templates/Search/Main.html
Labels: 🐛 bug

#1558 [BUGFIX] Fix displaying for missing title
  .github/phpstan.neon
  Classes/Common/SolrPaginator.php
  Classes/Controller/CollectionController.php
  Classes/Controller/ListViewController.php
  Resources/Private/Partials/ListView/SearchHits.html
  Resources/Private/Templates/ListView/Main.html
  Resources/Private/Templates/Search/Main.html
Labels: 🐛 bug

#1565 [MAINTENANCE] Use package softcreatr/jsonpath instead of flow/jsonpath
  Classes/Common/IiifManifest.php
  composer.json
Labels: 🛠 maintenance

#1566 [BUGFIX] Sync listview with facets and fix wrong hitcount
  Classes/Common/Solr/SolrSearch.php
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1574 [BUGFIX] Fix `showSorted` action
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1575 [BUGFIX] Fix `showSorted` action
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1577 [BUGFIX] Return if collection is not set
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1578 [FEATURE] Validation form plugin
  Classes/Controller/ValidationFormController.php
  Classes/Middleware/DOMDocumentValidation.php
  Classes/Validation/AbstractDlfValidationStack.php
  Classes/Validation/XmlSchemasValidator.php
  Configuration/FlexForms/ValidationForm.xml
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TsConfig/ContentElements.tsconfig
  Configuration/TypoScript/setup.typoscript
  Documentation/Developers/Validation.rst
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Templates/ValidationForm/Main.html
  Resources/Public/Icons/tx-dlf-validationform.svg
  Resources/Public/JavaScript/ValidationForm/ValidationForm.js
  Tests/Unit/Validation/DOMDocumentValidationStackTest.php
  Tests/Unit/Validation/XmlSchemasValidatorTest.php
  ext_localconf.php
Labels: ⚙ feature

#1581 [BUGFIX] Fix null pointer exception when calling musial structure
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1531 [BUGFIX] Move fullscreen to own section
  Classes/Controller/NavigationController.php
  Resources/Private/Templates/Navigation/Main.html
Labels: 🐛 bug

#1532 [BUGFIX] Add counter to identify image manipulation button
  Resources/Public/JavaScript/PageView/ImageManipulationControl.js
  Resources/Public/JavaScript/PageView/PageView.js
Labels: 🐛 bug

#1568 [BUGFIX] Display author URI as an external link
  Classes/Command/BaseCommand.php
  Classes/Controller/MetadataController.php
  Classes/Format/Mods.php
  Resources/Private/Data/MetadataDefaults.json
  Resources/Private/Partials/Metadata/Entries.html
  Resources/Private/Partials/Metadata/ExternalLinkEntry.html
Labels: 🐛 bug
