Repository kitodo/kitodo-presentation, pull requests merged in 2025-02, with the labels that each got.

#1450 [BUGFIX] Run tests with Solr 9.7.x
  Build/Test/docker-compose.yml
Labels: 🐛 bug

#1451 [BUGFIX] Run tests with Solr 9.7.x
  Build/Test/docker-compose.yml
Labels: 🐛 bug

#1411 [MAINTENANCE] Filter array for empty search parameters
  .github/phpstan.neon
  Classes/Controller/ListViewController.php
  Classes/Controller/SearchController.php
Labels: 🛠 maintenance

#1418 [BUGFIX] Check for undefined array key for fileGrp in mets:fileSec
  Classes/Controller/ToolboxController.php
Labels: 🐛 bug

#1420 [FEATURE] Add MIME type and file extension Helper methods
  Classes/Common/Helper.php
  Classes/Controller/ToolboxController.php
Labels: ⚙ feature

#1421 [BUGFIX] Handle missing 'DEFAULT' fileGrp in METS
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1423 [BUGFIX] Catch several issues with illegal operations on NULL
  Classes/Command/BaseCommand.php
  Classes/Command/IndexCommand.php
  Classes/Common/MetsDocument.php
  Classes/Controller/MetadataController.php
Labels: 🐛 bug

#1426 [BUGFIX] Fix runtime error for OAI-PMH access without verb
  Classes/Controller/OaiPmhController.php
  Classes/Domain/Repository/CollectionRepository.php
Labels: 🐛 bug

#1430 [BUGFIX] Fixes for runtime issues noticed in tests with main branch
  Classes/Controller/OaiPmhController.php
Labels: 🐛 bug

#1433 [BUGFIX] Update hide/show of loading and clearing elements
  Resources/Public/JavaScript/PageView/SearchInDocument.js
Labels: 🐛 bug

#1434 [BUGFIX] Re-introduce search for coordinates in ol.Feature Array
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🐛 bug

#1435 [MAINTENANCE] Clear document cache if force reload is true
  Classes/Common/AbstractDocument.php
Labels: 🛠 maintenance

#1436 [BUGFIX] Re-introduce search for coordinates in ol.Feature Array
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: 🐛 bug

#1438 [BUGFIX] Fix passing page id in ToolboxController - but keep viewArray Key
  Classes/Controller/ToolboxController.php
Labels: 🐛 bug

#1440 [MAINTENANCE] Update to relative path for dotenv in functional tests
  Tests/Functional/FunctionalTestCase.php
Labels: 🛠 maintenance

#1444 [BUGFIX] Fix displaying extended search fields
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1445 [BUGFIX] Fix displaying extended search fields
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1447 [BUGFIX] Pass correctly collection uid to list of search parameters
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1446 [BUGFIX] Fix displaying extended search fields
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1448 [BUGFIX] Pass correctly collection uid to list of search parameters
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1449 [BUGFIX] Pass correctly collection uid to list of search parameters
  Classes/Controller/CollectionController.php
Labels: 🐛 bug

#1441 [FEATURE] Include facets from all associated metadata sections for fulltext pages
  Classes/Common/Indexer.php
Labels: ⚙ feature

#1452 [BUGFIX] Remove old code relict which creates wrong log entries
  Classes/Controller/OaiPmhController.php
Labels: 🐛 bug

#1453 [BUGFIX] Avoid recursion in function `Solr::getNextCoreNumber`
  Classes/Common/Solr/Solr.php
Labels: 🐛 bug

#1456 [CONFIGURATION] Do not run the GitHub action deploy job in forks
  .github/workflows/documentation.yml
Labels: 📂 configuration

#1454 [MAINTENANCE] Use https for openarchives.org, kitodo.org and slub-dresden.de
  Classes/Controller/OaiPmhController.php
  Documentation/Introduction/Index.rst
  Resources/Public/Stylesheets/OaiPmh.xsl
  Tests/Fixtures/Common/documents_1.csv
  Tests/Fixtures/Common/documents_1.solr.json
  Tests/Fixtures/Common/documents_fulltext.csv
  Tests/Fixtures/Common/documents_fulltext.solr.json
  Tests/Fixtures/Format/modsAuthorNoAutRoleTerm.xml
  Tests/Fixtures/Format/modsAuthorWithAutRoleTerm.xml
  Tests/Fixtures/Format/modsOriginInfo.xml
  Tests/Fixtures/Format/modsOriginInfoWithEditionElectronicEd.xml
  Tests/Fixtures/MetsDocument/av_beispiel.xml
  Tests/Functional/Api/OaiPmhTest.php
Labels: 🛠 maintenance

#1457 [MAINTENANCE] Update composer.lock
  composer.lock
Labels: 🛠 maintenance

#1380 [FEATURE] Seamless document browsing
  Classes/Controller/NavigationController.php
  Classes/Domain/Repository/DocumentRepository.php
  Configuration/FlexForms/Navigation.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Templates/Navigation/Main.html
Labels: ⚙ feature

#1458 [MAINTENANCE] Drop support for PHP 7.4 and 8.0
  .github/workflows/tests.yml
  Build/Test/runTests.sh
  DEVELOPMENT.md
  composer.json
  ext_emconf.php
Labels: 🛠 maintenance

#1459 [BUGFIX] Filter `null` collections
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1460 [BUGFIX] Filter `null` collections
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1461 [BUGFIX] Filter `null` collections
  Classes/Common/Solr/SolrSearch.php
Labels: 🐛 bug

#1422 [FEATURE] Implement `UseGroupsConfiguration` class
  Classes/Common/AbstractDocument.php
  Classes/Common/FullTextReader.php
  Classes/Common/IiifManifest.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
  Classes/Configuration/UseGroupsConfiguration.php
  Classes/Controller/AbstractController.php
  Classes/Controller/AudioPlayerController.php
  Classes/Controller/PageGridController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/ToolboxController.php
  Configuration/FlexForms/Toolbox.xml
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_labels.xlf
  Tests/Functional/FunctionalTestCase.php
  ext_conf_template.txt
Labels: ⚙ feature

#1464 [BUGFIX] Remove Score Filegroup out of configKeys
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1465 [BUGFIX] Restore merging of arrays for physical nodes
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1466 [BUGFIX] Restore merging of arrays for physical nodes
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1467 [BUGFIX] Restore merging of arrays for physical nodes
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1468 [BUGFIX] Fix several runtime issues
  Classes/Command/BaseCommand.php
  Classes/Common/Indexer.php
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1473 [MAINTENANCE] Format XML output of OAI-PMH
  Classes/Controller/OaiPmhController.php
Labels: 🛠 maintenance

#1475 [BUGFIX] Trim id for full text element
  Resources/Public/JavaScript/PageView/FulltextControl.js
Labels: 🐛 bug

#1477 [BUGFIX] Trim id for full text element
  Resources/Public/JavaScript/PageView/FulltextControl.js
Labels: 🐛 bug

#1476 [BUGFIX] Trim id for full text element
  Resources/Public/JavaScript/PageView/FulltextControl.js
Labels: 🐛 bug

#1479 [BUGFIX] Add missing `useGroupsConfiguration` initialization in `AbstractController`
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1482 [BUGFIX] Add missing label for tx_dlf_tokens
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_labels.xlf
Labels: 🐛 bug

#1483 [BUGFIX] Allow OAI-PMH set names which are required for DINI
  Classes/Command/BaseCommand.php
  Configuration/TCA/tx_dlf_collections.php
Labels: 🐛 bug

#1406 [FEATURE] Add caching to pagegrid
  Classes/Controller/PageGridController.php
  ext_localconf.php
Labels: ⚙ feature

#1485 [FEATURE] [BUGFIX] Support for musical sources and compositas
  Classes/Common/MetsDocument.php
  Classes/Controller/AbstractController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageViewController.php
  Classes/Controller/ToolboxController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/Toolbox/Main.html
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/ScoreControl.js
  Resources/Public/JavaScript/PageView/ScoreUtility.js
Labels: 🐛 bug, ⚙ feature

#1498 [BUGFIX] Fix display for pagination
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug

#1499 [BUGFIX] Implement display of single collection in `CollectionController`
  Classes/Controller/CollectionController.php
  Configuration/FlexForms/Collection.xml
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Templates/Collection/Show.html
Labels: 🐛 bug

#1395 [FEATURE] 3D viewer selection
  Classes/Configuration/UseGroupsConfiguration.php
  Classes/Controller/ToolboxController.php
  Documentation/Developers/Embedded3DViewer.rst
  Documentation/Plugins/Index.rst
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_labels.xlf
  Resources/Private/Templates/Toolbox/Main.html
  ext_conf_template.txt
Labels: ⚙ feature

#1500 [BUGFIX] Refactor providing asset path for wildwebmidi.data
  Classes/Controller/AbstractController.php
  Classes/Controller/PageViewController.php
  Configuration/TypoScript/setup.typoscript
  Resources/Public/JavaScript/WildWebMidi/wildwebmidi.js
Labels: 🐛 bug

#1501 [BUGFIX] Add undefined constant check
  Resources/Public/JavaScript/WildWebMidi/wildwebmidi.js
Labels: 🐛 bug
