Repository kitodo/kitodo-presentation, pull requests merged in 2025-03, with the labels that each got.

#1503 [BUGFIX] Remove `excludes` from `FlexForms`
  Configuration/FlexForms/AudioPlayer.xml
  Configuration/FlexForms/Basket.xml
  Configuration/FlexForms/Calendar.xml
  Configuration/FlexForms/Collection.xml
  Configuration/FlexForms/Feeds.xml
  Configuration/FlexForms/ListView.xml
  Configuration/FlexForms/Metadata.xml
  Configuration/FlexForms/Navigation.xml
  Configuration/FlexForms/OaiPmh.xml
  Configuration/FlexForms/PageGrid.xml
  Configuration/FlexForms/PageView.xml
  Configuration/FlexForms/Search.xml
  Configuration/FlexForms/Statistics.xml
  Configuration/FlexForms/TableOfContents.xml
  Configuration/FlexForms/Toolbox.xml
  Configuration/FlexForms/View3D.xml
Labels: 🐛 bug

#1504 [BUGFIX] Fix calendar view
  Classes/Controller/CalendarController.php
Labels: 🐛 bug

#1507 [BUGFIX] Remove double assignment for `extendedFields`
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1508 [BUGFIX] Enable suggester before action exits with empty search parameters
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1509 [MAINTENANCE] Improvements for extended search
  Classes/Controller/SearchController.php
Labels: 🛠 maintenance

#1510 [BUGFIX] Enable suggester before action exits with empty search parameters
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1511 [MAINTENANCE] Declare `makeFacetsMenuArray()` function as `private`
  Classes/Controller/SearchController.php
Labels: 🛠 maintenance

#1486 [BUGFIX] Generate database documentation via typo3 command
  Build/Documentation/dbdocs/generate.php
  Build/Documentation/dbdocs/public/typo3
  Build/Documentation/dbdocs/public/typo3conf/LocalConfiguration.php
  Build/Documentation/dbdocs/public/typo3conf/PackageStates.php
  Build/Documentation/dbdocs/public/typo3conf/ext/dlf
  Classes/Command/DbDocs/Generator.php
  Classes/Command/DbDocs/RstSection.php
  Classes/Command/DbDocsCommand.php
  Configuration/Services.yaml
  DEVELOPMENT.md
  Documentation/Developers/Database.rst
  composer.json
Labels: 🐛 bug, 📖 documentation

#1512 [BUGFIX] Fix reading parameters in `SearchSuggest` middleware
  Classes/Middleware/SearchSuggest.php
Labels: 🐛 bug

#1513 [BUGFIX] Ensure proper type casting and null handling in Helper and MetsDocument classes
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1514 [BUGFIX] Fix runtime exception while running `kitodo:index`
  Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php
Labels: 🐛 bug

#1540 [BUGFIX] Return response instead of throwing an exception
  Classes/Middleware/SearchSuggest.php
Labels: 🐛 bug

#1542 [BUGFIX] Add `currentDocument` to view even if search params are empty
  Classes/Controller/SearchController.php
Labels: 🐛 bug

#1524 [BUGFIX] Display `<` an `>` instead of escaped strings
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug

#1537 [MAINTENANCE] Use local OAI-PMH.xsd for CI tests
  Tests/Fixtures/OaiPmh/OAI-PMH.xsd
  Tests/Unit/Validation/DOMDocumentValidationStackTest.php
Labels: 🛠 maintenance

#1544 [BACKPORT] Use local OAI-PMH.xsd for CI tests
  Tests/Fixtures/OaiPmh/OAI-PMH.xsd
  Tests/Unit/Validation/DOMDocumentValidationStackTest.php
Labels: ♻ backport

#1505 [BUGFIX] Explicitly declare nullable function parameters
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1523 [BUGFIX] Adjust reading and assigning `pageUid`
  Classes/Controller/AbstractController.php
  Classes/Controller/ToolboxController.php
  Resources/Private/Templates/Toolbox/Main.html
Labels: 🐛 bug

#1525 [BUGFIX] Display `<` an `>` instead of escaped strings
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug

#1529 [BUGFIX] Display [no title] for documents without title
  Resources/Private/Partials/ListView/Results.html
Labels: 🐛 bug

#1530 [BUGFIX] Display [no title] for documents without title
  Resources/Private/Partials/ListView/Results.html
Labels: 🐛 bug

#1536 [BUGFIX] Fix caching for classes IiifManifest and MetsDocument
  Classes/Common/AbstractDocument.php
  Classes/Common/IiifManifest.php
  Classes/Common/MetsDocument.php
Labels: 🐛 bug

#1541 [BUGFIX] Return response instead of throwing an exception
  Classes/Middleware/SearchSuggest.php
Labels: 🐛 bug

#1534 [MAINTENANCE] Remove bugfix versions of TYPO3 from dependencies
  composer.json
Labels: 🛠 maintenance

#1547 [BUGFIX] Fix position of }
  Resources/Private/Partials/Lists/Pagination.html
Labels: 🐛 bug

#1549 [BUGFIX] Correctly get pageId from request in AbstractController in TYPO3 v12
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1554 [BUGFIX] Fix condition in conditional statement
  Classes/Controller/AbstractController.php
Labels: 🐛 bug

#1559 [DOCUMENTATION] Fix documentation for `kitodo:dbdocs`
  Classes/Command/DbDocs/Generator.php
Labels: 📖 documentation

#1560 [FEATURE] Always show OAI-PMH request type
  Resources/Public/Stylesheets/OaiPmh.xsl
Labels: ⚙ feature
