Repository kitodo/kitodo-presentation, pull requests merged in 2025-06, with the labels that each got.

#1573 [MAINTENANCE] Fix some issues reported by PHPStan
  .github/phpstan.neon
  Classes/Common/AbstractDocument.php
  Classes/Common/Helper.php
  Classes/Common/Indexer.php
  Classes/Common/Solr/Solr.php
  Classes/Common/Solr/SolrSearch.php
  Classes/Controller/OaiPmhController.php
  ext_localconf.php
Labels: 🛠 maintenance

#1612 [BUGFIX] Translate alt text for thumbnail
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/ListView/Results.html
Labels: 🐛 bug

#1615 [MAINTENANCE] Format translation files
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_be.xlf
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/de.locallang_media.xlf
  Resources/Private/Language/de.locallang_mod_newtenant.xlf
  Resources/Private/Language/de.locallang_structure.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Language/locallang_labels.xlf
  Resources/Private/Language/locallang_media.xlf
  Resources/Private/Language/locallang_mod_newtenant.xlf
  Resources/Private/Language/locallang_structure.xlf
  Resources/Private/Language/locallang_tasks.xlf
Labels: 🛠 maintenance

#1617 [BUGFIX] Fix getting author name in `Indexer`
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1619 [BUGFIX] Fix getting author name in `Indexer`
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1622 [MAINTENANCE] Use the same default `userAgent` as defined in extension configuration
  Classes/Common/Helper.php
  Classes/Eid/PageViewProxy.php
  Tests/Functional/Api/PageViewProxyTest.php
Labels: 🛠 maintenance

#1629 [BUGFIX] Fix variable name for metadata authors
  Classes/Command/BaseCommand.php
Labels: 🐛 bug

#1631 [BUGFIX] Check for `docPage` array key
  Classes/Controller/PageViewController.php
Labels: 🐛 bug

#1616 [MAINTENANCE] Break up duplicated parts of `Results` template
  Resources/Private/Partials/ListView/Results.html
  Resources/Private/Partials/ListView/ResultsThumbnailMetadata.html
  Resources/Private/Partials/ListView/ResultsTitleMetadata.html
  Resources/Private/Partials/ListView/ResultsTypeMetadata.html
Labels: 🛠 maintenance

#1628 [BUGFIX] Add option for inserting all cookies into request
  Classes/Common/Helper.php
  Classes/Eid/PageViewProxy.php
  Resources/Private/Language/de.locallang_labels.xlf
  Resources/Private/Language/locallang_labels.xlf
  ext_conf_template.txt
Labels: 🐛 bug

#1630 [BUGFIX] Display correct error message for indexing
  Classes/Command/IndexCommand.php
  Classes/Common/Indexer.php
Labels: 🐛 bug

#1638 [MAINTENANCE] Replace usage of `strpos()`
  Classes/Command/DbDocs/Generator.php
  Classes/Common/AbstractDocument.php
  Classes/Common/Helper.php
  Classes/Common/MetsDocument.php
  Classes/Controller/MediaPlayerController.php
  Classes/Updates/MigrateSettings.php
Labels: 🛠 maintenance

#1639 [FEATURE] Handle TEI fulltexts
  Configuration/TypoScript/setup.typoscript
  Resources/Public/JavaScript/PageView/FullTextUtility.js
  Resources/Public/JavaScript/PageView/FulltextControl.js
  Resources/Public/JavaScript/PageView/FulltextDownloadControl.js
  Resources/Public/JavaScript/PageView/PageView.js
  Resources/Public/JavaScript/PageView/TeiParser.js
  Resources/Public/JavaScript/PageView/Utility.js
Labels: ⚙ feature

#1641 [MAINTENANCE] Adjustments in repository classes
  .github/phpstan.neon
  Classes/Domain/Repository/BasketRepository.php
  Classes/Domain/Repository/CollectionRepository.php
  Classes/Domain/Repository/DocumentRepository.php
  Classes/Domain/Repository/FormatRepository.php
  Classes/Domain/Repository/LibraryRepository.php
  Classes/Domain/Repository/MailRepository.php
  Classes/Domain/Repository/MetadataRepository.php
  Classes/Domain/Repository/PrinterRepository.php
  Classes/Domain/Repository/SolrCoreRepository.php
  Classes/Domain/Repository/StructureRepository.php
  Classes/Domain/Repository/TokenRepository.php
Labels: 🛠 maintenance

#1642 [BUGFIX] Fix return type for magic get `record_id`
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1635 [MAINTENANCE] Insert metadata format in Kitodo storage
  Classes/Common/AbstractDocument.php
  Classes/Controller/Backend/NewTenantController.php
  Classes/Updates/FormatUpdater.php
  Configuration/TCA/tx_dlf_formats.php
  Tests/Fixtures/Common/metadata.csv
  Tests/Fixtures/MetsDocument/metadata_mets.csv
  Tests/Fixtures/Repository/metadata.csv
  ext_localconf.php
Labels: 🛠 maintenance

#1645 [MAINTENANCE] Adjustments in functional test classes - part 2
  Tests/Functional/Api/OaiPmhTest.php
  Tests/Functional/Api/PageViewProxyDisabledTest.php
  Tests/Functional/Api/PageViewProxyTest.php
  Tests/Functional/Common/HelperTest.php
  Tests/Functional/Common/IiifUrlReaderTest.php
  Tests/Functional/Common/MetsDocumentTest.php
  Tests/Functional/Common/SolrIndexingTest.php
  Tests/Functional/Common/SolrSearchQueryTest.php
  Tests/Functional/Common/SolrSearchTest.php
  Tests/Functional/Common/SolrTest.php
  Tests/Functional/FunctionalTestCase.php
  Tests/Functional/Repository/CollectionRepositoryTest.php
  Tests/Functional/Repository/DocumentRepositoryTest.php
  Tests/Functional/Repository/MailRepositoryTest.php
  Tests/Functional/Repository/MetatdataRepositoryTest.php
  Tests/Functional/Repository/TokenRepositoryTest.php
Labels: 🛠 maintenance

#1646 [MAINTENANCE] Rename and add missing PHPDoc to time code conversion function
  Classes/Common/Helper.php
  Classes/Common/MetsDocument.php
  Tests/Unit/Common/HelperTest.php
Labels: 🛠 maintenance

#1647 [MAINTENANCE] Change way of the document validation exclusion for `record_id`
  Classes/Common/AbstractDocument.php
  Classes/Common/MetsDocument.php
  Classes/Validation/DocumentValidator.php
  Tests/Unit/Validation/DocumentValidatorTest.php
Labels: 🛠 maintenance

#1651 [BUGFIX] Add function for deleting single document cache instance
  Classes/Command/BaseCommand.php
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1653 [BUGFIX] Add function for deleting single document cache instance
  Classes/Command/BaseCommand.php
  Classes/Common/AbstractDocument.php
Labels: 🐛 bug

#1652 [MAINTENANCE] Replace `switch` with `match` expression
  Classes/Controller/CalendarController.php
  Classes/Controller/OaiPmhController.php
  Classes/Controller/SearchController.php
  Classes/Controller/ToolboxController.php
  Classes/Eid/PageViewProxy.php
Labels: 🛠 maintenance

#1657 Revert "[BUGFIX] Iterate over documents inside `SolrSearch`"
  Classes/Common/Solr/SolrSearch.php
  Classes/Common/SolrPaginator.php
Labels: 🐛 bug
