Repository kitodo/kitodo-presentation, pull requests merged in 2025-07, with the labels that each got.

#1660 [BUGFIX] Fixes navigation URL encoding and measure navigation
  Classes/Controller/AbstractController.php
  Classes/Controller/NavigationController.php
  Classes/Controller/PageViewController.php
  Resources/Private/Templates/Navigation/Main.html
Labels: 🐛 bug

#1668 [BUGFIX] Fix displaying of metadata
  Classes/Controller/MetadataController.php
  Classes/Controller/PageViewController.php
Labels: ☇ bug

#1669 [BUGFIX] Ensure 'fulltext' parameter is checked before accessing in SolrSearch
  Classes/Common/Solr/SolrSearch.php
Labels: ☇ bug

#1675 [MAINTENANCE] DlfMediaPlayer UI updates regarding to shaka-player UI update
  Build/package-lock.json
  Resources/Private/Less/DlfMediaPlayer.less
  Resources/Private/Less/DlfMediaPlayer/DlfMediaPlayer.less
  Resources/Private/Less/DlfMediaPlayer/ShakaFrontend.less
  Resources/Private/Less/SlubMediaPlayer/SlubMediaPlayer.less
  Resources/Private/Less/SlubMediaPlayer/modals/BookmarkModal.less
  Resources/Private/Less/SlubMediaPlayer/modals/ScreenshotModal.less
  Resources/Public/Css/DlfMediaPlayerStyles.css
  Resources/Public/Css/DlfMediaVendor.css
  Resources/Public/JavaScript/DlfMediaPlayer/DlfMediaPlayer.js
  Resources/Public/JavaScript/DlfMediaPlayer/DlfMediaVendor.js
  Resources/Public/JavaScript/DlfMediaPlayer/DlfMediaVendor.js.LICENSE.txt
Labels: ⟳ maintenance
